export {
  assertDerivedSurfaceFreshForRender,
  CCDocumentTransaction,
  clearColorCycleLayerDocumentsForOwner,
  ColorCycleLayerDocument,
  coalesceColorCycleDirtyRects,
  deleteColorCycleLayerDocumentForOwner,
  getColorCycleLayerDocumentForOwner,
  hasColorCycleLayerDocumentForOwner,
  isDerivedSurfaceStale,
  registerColorCycleLayerDocumentOwnerAlias,
  setColorCycleLayerDocumentForOwner,
  type ColorCycleDirtyRect,
  type ColorCycleLayerDocumentAuditEntry,
  type ColorCycleLayerDocumentArchiveRefs,
  type ColorCycleLayerDirtyBatch,
  type ColorCycleLayerDocumentOptions,
  type ColorCycleLayerDocumentRead,
  type ColorCycleLayerDocumentResidency,
  type ColorCycleLayerDocumentRuntimePolicy,
  type DerivedSurface,
  type DerivedSurfaceRenderAssertionOptions,
} from './ColorCycleLayerDocument';

export {
  COLOR_CYCLE_DOCUMENT_CONTRACT_KEYS,
  COLOR_CYCLE_DOCUMENT_CANONICAL_PIXEL_BUFFERS,
  COLOR_CYCLE_DOCUMENT_FIELD_MAPPING,
  COLOR_CYCLE_STROKE_FLOW_KEY,
  COLOR_CYCLE_STROKE_GRADIENT_DEF_ID_KEY,
  COLOR_CYCLE_STROKE_GRADIENT_ID_KEY,
  COLOR_CYCLE_STROKE_PAINT_KEY,
  COLOR_CYCLE_STROKE_PHASE_KEY,
  COLOR_CYCLE_STROKE_SPEED_KEY,
  mapDocumentSnapshotToArchiveState,
  mapDocumentSnapshotToGobletBrushState,
  type ColorCycleLayerDocumentSnapshot,
  type ColorCycleLayerDocumentState,
  type DocumentSnapshotToGobletBrushStateOptions,
} from './colorCycleDocumentContract';

export {
  getDerivedSurfaceBuiltFromVersion,
  markDerivedSurfaceBuiltFromVersion,
  type VersionedDerivedSurface,
} from './derivedSurfaceMetadata';

export {
  completeDefaultColorCycleMotionBuffers,
  hasCanonicalColorCyclePaint,
  hasGradientBindingBuffers,
  normalizeColorCycleLayerDocumentState,
  validateColorCycleDocumentStateDimensions,
  type ColorCycleDocumentStateResult,
  type NormalizeColorCycleDocumentStateOptions,
} from './documentState';

export {
  cloneStrokeSnapshotBuffers,
  type ColorCycleStrokeBuffers,
  type ColorCycleStrokeSnapshot,
  type ColorCycleStrokeSnapshotSource,
} from './colorCycleStrokeSnapshot';

export {
  brushStateHasCcPayload,
  brushStateHasRuntimeStrokeBufferAuthority,
  bufferHasNonZeroPayload,
  hasCcPayload,
  persistedStrokeDataHasExportableColorCycleBuffers,
} from './colorCyclePayloadGuards';

export {
  resolveColorCyclePaintCoverageFromSerializedState,
  type ColorCyclePaintCoverage,
  type ColorCyclePaintCoverageFallbackDimensions,
} from './paintCoverage';

export {
  applyColorCycleTransparencyMaskToPaintSnapshot,
  buildColorCycleCanonicalSelectionPayload,
  buildColorCycleCanonicalSelectionPayloadFromSnapshot,
  buildColorCyclePaintDeltaMask,
  buildColorCycleRuntimePaintSnapshot,
  captureColorCyclePaintRegion,
  cloneColorCyclePaintSnapshotPaintMask,
  colorCycleRuntimePaintSnapshotToBrushSnapshot,
  colorCyclePaintSnapshotHasPayload,
  getColorCycleSerializedStatePaintByteLength,
  rebuildColorCycleSerializedStateRegion,
  scaleColorCyclePaintSnapshotNearest,
  summarizeColorCycleSelectionPaint,
  type ColorCyclePaintMask,
  type ColorCyclePaintMaskRegion,
  type ColorCyclePaintSnapshot,
  type ColorCyclePaintTransparencyMaskOptions,
  type ColorCycleCanonicalSelectionPayload,
  type ColorCycleRuntimePaintSnapshot,
  type ColorCycleSelectionPaintSummary,
} from './paintDeltaMask';

export {
  getColorCycleLegacyLayerBuffer,
  getColorCycleLegacyLayerBufferByteLength,
  getColorCycleLegacyLayerBuffers,
  type ColorCycleLegacyLayerBufferKey,
  type ColorCycleLegacyLayerBuffers,
} from './legacyLayerBufferAccess';

export {
  restoreColorCycleBrushesWithDocumentHydration,
  type ColorCycleRestoreBrushFactory,
  type RestoreColorCycleBrushesHydrationDependencies,
  type RestoreColorCycleBrushesOptions,
} from './hydration';

export {
  materializeColorCycleLayer,
  materializeRestoredColorCycleSurface,
  resolveColorCycleRuntimeSurface,
  type ColorCycleRuntimeBrush,
  type EnsureColorCycleLayerRuntimeTarget,
  type MaterializeColorCycleLayerOptions,
  type MaterializeColorCycleLayerResult,
  type ResolveColorCycleRuntimeSurfaceOptions,
} from './materializeColorCycleLayer';

export {
  attachLegacyColorCycleTopLevelBuffers,
  deleteLegacyColorCycleTopLevelBuffers,
  hasLegacyColorCycleTopLevelBuffers,
  readLegacyColorCycleTopLevelBufferRefs,
  readMutableLegacyColorCycleTopLevelBuffers,
  readLegacyColorCycleTopLevelBuffers,
  type LegacyColorCycleTopLevelBufferRefs,
  type LegacyColorCycleTopLevelBuffers,
} from './legacyTopLevelBuffers';

export {
  repairLegacyColorCycleLayer,
  type ColorCycleLegacyRepairFailureReason,
  type ColorCycleLegacyRepairResult,
} from './legacyRepair';

export {
  brushStateHasColorCyclePaintPayload,
  ccPayloadHasBytes,
  ccPayloadHasNonZeroByte,
  ccSnapshotHasPaintPayload,
  decodeBase64ArrayBuffer,
  extractCanonicalBrushStateLayerSnapshot,
  hasRecoverableColorCycleRuntimeSource,
  layerHasCanonicalColorCyclePaintPayload,
  normalizeCcPayloadArrayBuffer,
  resolveColorCycleRuntimeRestore,
  type CcRuntimeAnimatorIndexSnapshot,
  type CcRuntimeLayerSnapshot,
  type CcRuntimeRestoreAction,
  type CcRuntimeStrokeSnapshot,
} from './resolveColorCycleRuntimeRestore';

export {
  applyColorCycleBrushPaintPatchToBuffers,
  applyColorCycleBrushPaintPatchToRuntime,
  applyColorCycleBrushLayerSnapshotToBuffers,
  applyColorCycleBrushLayerSnapshotToRuntime,
  bindColorCycleCommittedGradientDefToSlot,
  canApplyColorCycleBrushLayerSnapshotToRuntime,
  canApplyColorCycleBrushPaintPatchToRuntime,
  canReadColorCycleBrushLayerSnapshotFromRuntime,
  canRestoreColorCycleBrushSerializedStateToRuntime,
  clearColorCycleBrushStrokeStatesForOwner,
  clearColorCycleBrushStrokeStateForRestore,
  clearColorCycleBrushPersistenceLayerMetaForOwner,
  cloneColorCycleBrushLayerSnapshot,
  cloneColorCycleLayerStrokePaintBytes,
  cloneColorCycleSerializedBrushLayerSnapshotBuffers,
  cloneColorCycleBrushStateForLayerDuplicate,
  cloneColorCycleStrokeSnapshotBuffers,
  cloneColorCycleBrushPersistenceLayerMeta,
  createColorCycleHistoryLayerStrokeSnapshot,
  colorCycleBrushSnapshotHasPaintPayload,
  commitColorCycleBrushPaintPatchResultToStrokeState,
  commitColorCycleCommittedLayerStateToRuntime,
  colorCycleArrayBuffersEqual,
  commitColorCycleBrushLayerSnapshotApplyResultToStrokeState,
  cropColorCycleBrushLayerSnapshotRegion,
  ColorCycleBrushPersistenceMetaCache,
  createColorCycleCanonicalBrushStateFromSnapshot,
  createColorCycleCanonicalBrushStateFromDocumentSnapshot,
  createEmptyColorCycleBrushLayerSnapshot,
  createColorCycleBrushPersistenceLayerMetaFromLayerData,
  createColorCycleBrushDeserializeLayerApplyPlans,
  createColorCycleBrushDeserializeSettingsPatch,
  createColorCycleBrushSerializeSettings,
  createColorCycleBrushFullStateRestorePlan,
  createColorCycleBrushLayerSnapshotApplyPlan,
  createColorCycleBrushLayerSnapshotAnimatorSizingPlan,
  createColorCycleBrushLayerSnapshotBlockedAuditDetails,
  createColorCycleBrushLayerSnapshotClearAuditPlan,
  createColorCycleBrushLayerSnapshotDirtyBounds,
  createColorCycleBrushLayerSnapshotFallbackAnimationPlan,
  createColorCycleBrushLayerSnapshotMetadataPlan,
  createColorCycleBrushLayerSnapshotRestoreGuard,
  createColorCycleStorageLayerStrokeSnapshot,
  createColorCycleBrushRestoreBlockedClearAuditPlan,
  createColorCycleRuntimeRestoreIncomingSnapshot,
  createColorCycleLayerDocumentStateFromStrokeState,
  createEmptyColorCycleLayerDocumentState,
  createColorCycleCommittedLayerStoreSyncPatch,
  executeColorCycleBrushLayerSnapshotAnimatorSync,
  executeColorCycleBrushLayerSnapshotMetadataPlan,
  executeColorCycleBrushLayerSnapshotRuntimeApply,
  executeColorCycleBrushPaintPatchAnimatorSync,
  executeColorCycleBrushPaintPatchRuntimeApply,
  executeColorCycleCommittedLayerState,
  executeColorCycleBrushFullStateRestorePlan,
  getColorCycleBrushStrokeStateEntriesForOwner,
  getColorCycleBrushStrokeStateForOwner,
  getColorCycleBrushStrokeStateValuesForOwner,
  hasColorCycleBrushStrokeStateForOwner,
  mergeColorCycleBrushPersistenceLayerMetaForOwner,
  mergeColorCycleBrushPersistenceLayerMeta,
  readColorCycleBrushLayerSnapshot,
  readColorCycleBrushLayerSnapshotFromDocumentRead,
  readColorCycleBrushLayerSnapshotFromRuntime,
  readColorCycleCommittedLayerStateFromRuntime,
  readColorCycleBrushSerializedStateFromRuntime,
  registerColorCycleBrushLayerSnapshotRuntime,
  registerColorCycleBrushPaintPatchRuntime,
  registerColorCycleBrushPersistenceOwnerAlias,
  registerColorCycleBrushSerializedStateRuntime,
  remapColorCycleCommittedGradientSlot,
  restoreColorCycleBrushSerializedStateToRuntime,
  serializeColorCycleBrushState,
  setColorCycleBrushStrokeStateForOwner,
  setColorCycleBrushPersistenceLayerMeta,
  type BindColorCycleCommittedGradientDefToSlotOptions,
  type BindColorCycleCommittedGradientDefToSlotResult,
  type ColorCycleCommittedLayerRuntime,
  type ColorCycleCommittedLayerRuntimeRead,
  type ColorCycleCommittedGradientSlotRemapOptions,
  type ColorCycleCommittedGradientSlotRemapResult,
  type ColorCycleCommittedLayerStateOptions,
  type ColorCycleCommittedLayerStoreSyncPatch,
  type ExecuteColorCycleCommittedLayerStateOptions,
  type ColorCycleBrushAnimatorIndexInput,
  type ColorCycleBrushDeserializedLayerApplyPlan,
  type ColorCycleBrushFullStateRestorePlan,
  type ColorCycleBrushLayerSnapshot,
  type ColorCycleLayerStrokeSnapshot,
  type ColorCycleBrushLayerSnapshotApplyResult,
  type ColorCycleBrushLayerSnapshotMutableStrokeState,
  type ColorCycleBrushLayerSnapshotApplyPlan,
  type ColorCycleBrushLayerSnapshotAnimatorSizingPlan,
  type ColorCycleBrushLayerSnapshotBlockedAuditDetails,
  type ColorCycleBrushLayerSnapshotClearAuditPlan,
  type ColorCycleBrushLayerSnapshotAnimatorDimensions,
  type ColorCycleBrushLayerSnapshotFallbackAnimationPlan,
  type ColorCycleBrushLayerSnapshotFallbackFlowMode,
  type ColorCycleBrushLayerSnapshotRestoreActionKind,
  type ColorCycleBrushLayerSnapshotRestoreGuard,
  type ColorCycleBrushLayerSnapshotStrokeStateCommit,
  type ColorCycleBrushLayerSnapshotDirtyBounds,
  type ColorCycleBrushRestoreBlockedClearAuditDetails,
  type ColorCycleBrushRestoreBlockedClearAuditPlan,
  type CreateColorCycleBrushLayerSnapshotAnimatorSizingPlanOptions,
  type CreateColorCycleBrushLayerSnapshotBlockedAuditDetailsOptions,
  type CreateColorCycleBrushLayerSnapshotClearAuditPlanOptions,
  type CreateColorCycleBrushLayerSnapshotFallbackAnimationPlanOptions,
  type CreateColorCycleBrushLayerSnapshotRestoreGuardOptions,
  type CreateColorCycleBrushRestoreBlockedClearAuditPlanOptions,
  type ColorCycleBrushLayerSnapshotInput,
  type ColorCycleBrushLayerSnapshotMetadataPlan,
  type ColorCycleBrushPaintPatchStrokeStateCommit,
  type ExecuteColorCycleBrushLayerSnapshotAnimatorSyncOptions,
  type ExecuteColorCycleBrushLayerSnapshotMetadataPlanOptions,
  type ExecuteColorCycleBrushPaintPatchAnimatorSyncOptions,
  type ExecuteColorCycleBrushPaintPatchRuntimeApplyOptions,
  type ColorCycleBrushPaintPatchExtras,
  type ColorCycleBrushPaintPatchResult,
  type ColorCycleBrushPaintPatchRuntimeWriter,
  type ColorCycleBrushSerializedStateRuntimeReader,
  type ColorCycleBrushSerializedStateRuntimeWriter,
  type ColorCycleBrushPersistenceAnimator,
  type ColorCycleBrushPersistenceAnimatorState,
  type ColorCycleBrushPersistenceLayerMeta,
  type ColorCycleBrushPersistenceStrokeState,
  type ColorCycleBrushLayerSnapshotRuntimeReader,
  type ColorCycleBrushLayerSnapshotRuntimeWriter,
  type ExecuteColorCycleBrushFullStateRestorePlanOptions,
  type ColorCycleBrushRestoreLayerApplyPlan,
  type ColorCycleBrushRestoreLayerClearPlan,
  type ColorCycleBrushRestoreState,
  type ColorCycleBrushSerializeSettingsInput,
  type ColorCycleBrushSerializedLayer,
  type ColorCycleBrushSerializedSettings,
  type ColorCycleBrushSerializedState,
  type ColorCycleHistoryLayerStrokeSnapshot,
  type CreateColorCycleCanonicalBrushStateFromSnapshotOptions,
} from './brushPersistenceAdapter';

export {
  COLOR_CYCLE_RUNTIME_OWNER,
  type ColorCycleRuntimeOwnerProvider,
} from './brushPersistenceOwnerAlias';
