import fs from 'node:fs';
import path from 'node:path';

import {
  GOBLET2_LEGACY_SCHEMA_VERSION,
  GOBLET2_SCHEMA_VERSION,
  GOBLET_BRUSH_REQUIRED_BUFFERS,
  GOBLET_BRUSH_REQUIRED_SCALARS,
} from '@/lib/colorCycle/document/colorCycleDocumentContract';

import { createGoblet2Bundle } from './fixtures/goblet2Bundle';

const extractNamedExportConst = (source: string, name: string): string => {
  const marker = `export const ${name}`;
  const start = source.indexOf(marker);
  if (start === -1) {
    throw new Error(`Missing ${name}`);
  }
  const equalsIndex = source.indexOf('=', start);
  if (equalsIndex === -1) {
    throw new Error(`Missing initializer for ${name}`);
  }
  let depth = 0;
  for (let index = equalsIndex + 1; index < source.length; index += 1) {
    const char = source[index];
    if (char === '(' || char === '[' || char === '{') {
      depth += 1;
    } else if (char === ')' || char === ']' || char === '}') {
      depth -= 1;
    } else if (char === ';' && depth === 0) {
      return source.slice(start, index + 1);
    }
  }
  throw new Error(`Unterminated initializer for ${name}`);
};

const buildGeneratedGobletContractSource = (documentContract: string): string => {
  const exports = [
    'GOBLET2_FORMAT',
    'GOBLET2_SCHEMA_VERSION',
    'GOBLET2_LEGACY_SCHEMA_VERSION',
    'GOBLET_BRUSH_REQUIRED_BUFFERS',
    'GOBLET_BRUSH_REQUIRED_SCALARS',
    'GOBLET_BRUSH_MASK_FIELDS',
    'GOBLET_COLOR_CYCLE_BRUSH_MODE',
    'GOBLET_COLOR_CYCLE_RECOLOR_MODE',
  ];
  return exports.map((name) => extractNamedExportConst(documentContract, name)).join('\n\n');
};

describe('goblet2 bundle fixture', () => {
  it('emits a v2 format bundle with brush speed buffer', () => {
    const bundle = createGoblet2Bundle();
    expect(bundle.format).toBe('vessel-goblet2');
    expect(bundle.colorCycle?.schemaVersion).toBe(GOBLET2_SCHEMA_VERSION);
    const layer = bundle.layers[0];
    const brushState = layer.colorCycle?.brushState as { speedBuffer?: number[] } | undefined;
    expect(Array.isArray(brushState?.speedBuffer)).toBe(true);
    expect(brushState?.speedBuffer).toHaveLength(4);
  });

  it('keeps schema-version discipline tied to the compatibility contract', () => {
    const contractPath = path.resolve(process.cwd(), 'docs/color-cycle-compatibility-contract.md');
    const contract = fs.readFileSync(contractPath, 'utf8');
    expect(contract).toContain(`colorCycle.schemaVersion: ${GOBLET2_SCHEMA_VERSION}`);
    expect(contract).toContain('Bump `colorCycle.schemaVersion`');
    expect(contract).toContain('previous schema version (`N-1`)');
    expect(contract).toContain('fixture pinned to the old schema version');
    expect(contract).toContain('Silent semantic changes under the same `colorCycle.schemaVersion` are not allowed.');

    const legacyFixturePath = path.resolve(
      process.cwd(),
      'tests/fixtures/goblet2/legacy-schema-1-color-cycle.json',
    );
    const legacyFixture = JSON.parse(fs.readFileSync(legacyFixturePath, 'utf8')) as {
      format?: unknown;
      colorCycle?: { schemaVersion?: unknown };
      layers?: unknown[];
    };
    expect(legacyFixture.format).toBe('vessel-goblet2');
    expect(legacyFixture.colorCycle?.schemaVersion).toBe(GOBLET2_LEGACY_SCHEMA_VERSION);
    expect(legacyFixture.layers?.length).toBeGreaterThan(0);
  });

  it('keeps the generated Goblet2 runtime contract copy fresh', () => {
    const sourcePath = path.resolve(process.cwd(), 'src/lib/colorCycle/document/colorCycleDocumentContract.ts');
    const runtimeCopyPath = path.resolve(process.cwd(), 'public/goblet2/gobletPayloadContract.js');
    const source = fs.readFileSync(sourcePath, 'utf8');
    const runtimeCopy = fs.readFileSync(runtimeCopyPath, 'utf8');
    const expectedCopy = `// Auto-generated by scripts/build-goblet-runtime.mjs. Do not edit directly.\n${buildGeneratedGobletContractSource(source)}`;

    expect(runtimeCopy).toBe(expectedCopy);
    expect(runtimeCopy).toContain(`GOBLET2_SCHEMA_VERSION = ${GOBLET2_SCHEMA_VERSION}`);
    for (const buffer of GOBLET_BRUSH_REQUIRED_BUFFERS) {
      expect(runtimeCopy).toContain(`name: '${buffer.name}'`);
    }
    for (const scalar of GOBLET_BRUSH_REQUIRED_SCALARS) {
      expect(runtimeCopy).toContain(`name: '${scalar.name}'`);
    }
  });
});
