export const AUTO_CONVERT_MIN_SHAPES = 2;
export const AUTO_CONVERT_MAX_SHAPES = 200;
export const AUTO_CONVERT_MIN_FOCUS = 0;
export const AUTO_CONVERT_MAX_FOCUS = 100;
export const AUTO_CONVERT_MIN_RESOLUTION = 1;
export const AUTO_CONVERT_MAX_RESOLUTION = 64;
