export const PROJECT_FILE_EXTENSION = '.vs';
export const LEGACY_PROJECT_FILE_EXTENSION = '.tb';

export const PROJECT_FILE_MIME = 'application/zip';
export const LEGACY_PROJECT_FILE_MIME = 'application/json';

export const PROJECT_FILE_ACCEPT = [
  PROJECT_FILE_EXTENSION,
  LEGACY_PROJECT_FILE_EXTENSION
];

export const PROJECT_FILE_MIME_ACCEPT = [
  PROJECT_FILE_MIME,
  LEGACY_PROJECT_FILE_MIME
];
