import { contourFill } from './fillStrategies/contour';
import { hatchFill } from './fillStrategies/hatch';
import { delaunayFill } from './fillStrategies/delaunay';
import { dashesFill } from './fillStrategies/dashes';
import { flowFill } from './fillStrategies/flow';
import { stippleFill } from './fillStrategies/stipple';
import { sierraFill } from './fillStrategies/sierra';
import { noiseFill } from './fillStrategies/noise';
import { getParameterDefault, getParameterDefinition } from './parameters';
import { FillStrategy, ShapeFillId } from './types';

const strategyMap: Record<ShapeFillId, FillStrategy> = {
  hatch: {
    id: 'hatch',
    label: 'Hatch',
    defaults: {
      spacing: getParameterDefault('spacing'),
      rotation: 0,
      thickness: getParameterDefault('thickness'),
      variance: 0.35,
      organic: 0.7,
      segments: getParameterDefault('segments'),
      cross: false,
      seed: 0,
    },
    apply: hatchFill,
    adjustOrder: ['spacing'],
    ui: [
      {
        key: 'spacing',
        type: 'number',
        label: 'Spacing',
        min: 1,
        max: 200,
        step: 1,
        default: getParameterDefault('spacing'),
      },
      {
        key: 'variance',
        type: 'number',
        label: 'Spacing Jitter',
        min: 0,
        max: 1,
        step: 0.05,
        default: getParameterDefault('variance'),
      },
      {
        key: 'thickness',
        type: 'number',
        label: 'Line Width',
        min: 0.25,
        max: 6,
        step: 0.05,
        default: getParameterDefault('thickness'),
      },
      {
        key: 'segments',
        type: 'number',
        label: 'Segments',
        min: getParameterDefinition('segments').min,
        max: getParameterDefinition('segments').max,
        step: 1,
        default: getParameterDefault('segments'),
      },
      {
        key: 'organic',
        type: 'number',
        label: 'Organic Wobble',
        min: 0,
        max: 1,
        step: 0.05,
        default: 0.7,
      },
    ],
  },
  delaunay: {
    id: 'delaunay',
    label: 'Delaunay',
    defaults: {
      spacing: 22,
      rotation: 0,
      thickness: 1.1,
      variance: 0.35,
      organic: 0,
      seed: 0,
      delaunayVariation: getParameterDefault('delaunayVariation'),
    },
    apply: delaunayFill,
    adjustOrder: ['spacing'],
    ui: [
      {
        key: 'spacing',
        type: 'number',
        label: 'Spacing',
        min: 6,
        max: 200,
        step: 1,
        default: 22,
      },
      {
        key: 'variance',
        type: 'number',
        label: 'Jitter',
        min: 0,
        max: 1,
        step: 0.05,
        default: 0.35,
      },
      {
        key: 'thickness',
        type: 'number',
        label: 'Line Width',
        min: 0.2,
        max: 6,
        step: 0.1,
        default: 1.1,
      },
      {
        key: 'delaunayVariation',
        type: 'number',
        label: 'Variation',
        min: 0,
        max: 1.5,
        step: 0.05,
        default: getParameterDefault('delaunayVariation'),
      },
      {
        key: 'seed',
        type: 'number',
        label: 'Seed',
        min: 0,
        max: 999,
        step: 1,
        default: 0,
      },
    ],
  },
  contour: {
    id: 'contour',
    label: 'Contour',
    defaults: {
      spacing: 12,
      rotation: 0,
      thickness: 1,
      variance: 0.2,
      spacingWobble: 0.45,
    },
    apply: contourFill,
    adjustOrder: ['spacing'],
    ui: [
      {
        key: 'spacing',
        type: 'number',
        label: 'Spacing',
        min: 2,
        max: 400,
        step: 1,
        default: 12,
      },
      {
        key: 'variance',
        type: 'number',
        label: 'Variance',
        min: 0,
        max: 1,
        step: 0.05,
        default: 0.2,
      },
      {
        key: 'spacingWobble',
        type: 'number',
        label: 'S Wobble',
        min: 0,
        max: 1,
        step: 0.05,
        default: 0.45,
      },
      {
        key: 'thickness',
        type: 'number',
        label: 'Line Width',
        min: 0.2,
        max: 6,
        step: 0.1,
        default: 1,
      },
    ],
  },
  stipple: {
    id: 'stipple',
    label: 'Stipple',
    defaults: {
      spacing: 12,
      rotation: 0,
      thickness: 1,
      wobble: 0.45,
      seed: 0,
    },
    apply: stippleFill,
    adjustOrder: ['spacing'],
    ui: [
      {
        key: 'spacing',
        type: 'number',
        label: 'Spacing',
        min: 2,
        max: 200,
        step: 1,
        default: 12,
      },
      {
        key: 'wobble',
        type: 'number',
        label: 'Wobble',
        min: 0,
        max: 1,
        step: 0.05,
        default: 0.45,
      },
      {
        key: 'thickness',
        type: 'number',
        label: 'Dot Scale',
        min: 0.5,
        max: 5,
        step: 0.1,
        default: 1,
      },
    ],
  },
  noise: {
    id: 'noise',
    label: 'Noise',
    defaults: {
      spacing: 0.5,
      rotation: 0,
      thickness: 1,
      variance: 0,
      seed: 0,
      noiseScale: getParameterDefault('noiseScale'),
      noiseContrast: getParameterDefault('noiseContrast'),
      noiseThreshold: 0.5,
      noiseOctaves: getParameterDefault('noiseOctaves'),
      noiseRandomness: getParameterDefault('noiseRandomness'),
    },
    apply: noiseFill,
    adjustOrder: [],
    ui: [
      {
        key: 'spacing',
        type: 'number',
        label: 'Pixel Size',
        min: 0.1,
        max: 4,
        step: 0.1,
        default: 0.5,
      },
      {
        key: 'noiseThreshold',
        type: 'number',
        label: 'White Bias',
        min: 0,
        max: 1,
        step: 0.01,
        default: 0.5,
      },
      {
        key: 'thickness',
        type: 'number',
        label: 'Speck Size',
        min: 0.2,
        max: 4,
        step: 0.1,
        default: 1,
      },
      {
        key: 'noiseRandomness',
        type: 'number',
        label: 'Organic Randomness',
        min: 0,
        max: 1,
        step: 0.01,
        default: getParameterDefault('noiseRandomness'),
      },
      {
        key: 'seed',
        type: 'number',
        label: 'Seed',
        min: 0,
        max: 4096,
        step: 1,
        default: 0,
      },
    ],
  },
  sierra: {
    id: 'sierra',
    label: 'Sierra',
    defaults: {
      spacing: getParameterDefault('spacing'),
      rotation: getParameterDefault('rotation'),
      thickness: getParameterDefault('thickness'),
      sierraDensity: getParameterDefault('sierraDensity'),
      sierraResolution: getParameterDefault('sierraResolution'),
      variance: 0,
      seed: 0,
    },
    apply: sierraFill,
    adjustOrder: [],
    ui: [
      {
        key: 'sierraDensity',
        type: 'number',
        label: 'Density',
        min: 0,
        max: 1,
        step: 0.01,
        default: getParameterDefault('sierraDensity'),
      },
      {
        key: 'sierraResolution',
        type: 'number',
        label: 'Resolution',
        min: 1,
        max: 16,
        step: 1,
        default: getParameterDefault('sierraResolution'),
      },
    ],
  },
  dashes: {
    id: 'dashes',
    label: 'Dashes',
    defaults: {
      spacing: 10,
      rotation: 12,
      thickness: 3.5,
      variance: 0,
      seed: 0,
      dashLength: 3,
      dashLengthJitter: 0,
      dashWeightJitter: 0.25,
      scatter: 0,
      nearFalloff: 1,
      farFalloff: 1,
      angleDrift: 16,
      angleScale: 420,
    },
    apply: dashesFill,
    adjustOrder: ['spacing'],
    ui: [
      {
        key: 'spacing',
        type: 'number',
        label: 'Spacing',
        min: 2,
        max: 200,
        step: 1,
        default: 10,
      },
      {
        key: 'dashLength',
        type: 'number',
        label: 'Dash length (px)',
        min: 2,
        max: 200,
        step: 1,
        default: 3,
      },
      {
        key: 'dashLengthJitter',
        type: 'number',
        label: 'Length jitter (0–1)',
        min: 0,
        max: 1,
        step: 0.01,
        default: 0,
      },
      {
        key: 'thickness',
        type: 'number',
        label: 'Dash Weight',
        min: 0.2,
        max: 8,
        step: 0.1,
        default: 3.5,
      },
      {
        key: 'dashWeightJitter',
        type: 'number',
        label: 'Weight jitter (0–1)',
        min: 0,
        max: 1,
        step: 0.01,
        default: 0.25,
      },
      {
        key: 'scatter',
        type: 'number',
        label: 'Scatter (px)',
        min: 0,
        max: 120,
        step: 0.5,
        default: 0,
      },
      {
        key: 'nearFalloff',
        type: 'number',
        label: 'Near falloff',
        min: 0.15,
        max: 4,
        step: 0.05,
        default: 1,
      },
      {
        key: 'farFalloff',
        type: 'number',
        label: 'Far falloff',
        min: 0.15,
        max: 5,
        step: 0.05,
        default: 1,
      },
      {
        key: 'rotation',
        type: 'number',
        label: 'Direction (°)',
        min: 0,
        max: 180,
        step: 1,
        default: 12,
      },
      {
        key: 'angleDrift',
        type: 'number',
        label: 'Drift amount (°)',
        min: 0,
        max: 90,
        step: 1,
        default: 16,
      },
      {
        key: 'angleScale',
        type: 'number',
        label: 'Drift scale (px)',
        min: 10,
        max: 900,
        step: 5,
        default: 420,
      },
      {
        key: 'seed',
        type: 'number',
        label: 'Seed',
        min: 0,
        max: 4096,
        step: 1,
        default: 0,
      },
    ],
  },
  flow: {
    id: 'flow',
    label: 'Flow',
    defaults: {
      spacing: getParameterDefault('spacing'),
      rotation: 0,
      thickness: 1,
      variance: 0,
      seed: 0,
      flowSeedSpacing: getParameterDefault('flowSeedSpacing'),
      flowStepSize: getParameterDefault('flowStepSize'),
      flowMaxSteps: getParameterDefault('flowMaxSteps'),
      flowFieldStep: 8,
      flowUseOrthogonal: false,
    },
    apply: flowFill,
    adjustOrder: [],
    ui: [
      {
        key: 'flowSeedSpacing',
        type: 'number',
        label: 'Seed spacing (px)',
        min: 4,
        max: 200,
        step: 1,
        default: getParameterDefault('flowSeedSpacing'),
      },
      {
        key: 'flowStepSize',
        type: 'number',
        label: 'Step size (px/iter)',
        min: 0.25,
        max: 20,
        step: 0.25,
        default: getParameterDefault('flowStepSize'),
      },
      {
        key: 'flowMaxSteps',
        type: 'number',
        label: 'Max length',
        min: 10,
        max: 600,
        step: 5,
        default: getParameterDefault('flowMaxSteps'),
      },
    ],
  },
};

export function getFillStrategy(id: ShapeFillId): FillStrategy {
  const strategy = strategyMap[id];
  if (!strategy) {
    throw new Error(`Unknown shape fill strategy: ${id}`);
  }
  return strategy;
}

export function listFillStrategies(): FillStrategy[] {
  return Object.values(strategyMap);
}
