export {
  GOBLET2_FORMAT,
  GOBLET2_SCHEMA_VERSION,
  GOBLET_BRUSH_MASK_FIELDS,
  GOBLET_BRUSH_REQUIRED_BUFFERS,
  GOBLET_BRUSH_REQUIRED_SCALARS,
} from '@/lib/colorCycle/document/colorCycleDocumentContract';
