import { buildDrawingHandlersFinalizeRuntimeOptions } from '@/hooks/canvas/buildDrawingHandlersFinalizeRuntimeOptions';
import { buildDrawingHandlersPlaybackHandlersOptions } from '@/hooks/canvas/buildDrawingHandlersPlaybackHandlersOptions';
import { buildDrawingHandlersShapeLifecycleOptions } from '@/hooks/canvas/buildDrawingHandlersShapeLifecycleOptions';
import { buildDrawingHandlersStrokeLifecycleOptions } from '@/hooks/canvas/buildDrawingHandlersStrokeLifecycleOptions';
import type {
  RuntimeBridgeArgs,
  UseDrawingHandlersRuntimeSetupBridgeOptions,
} from '@/hooks/canvas/useDrawingHandlersRuntimeSetupBridge.types';

export const buildDrawingHandlersRuntimeBridgeArgs = ({
  refs,
  isPointerDownRef,
  project,
  storeRef,
  sampleColorAt,
  isBusyRef,
  shapeMode,
  toolsRef,
  captureCanvasToActiveLayer,
  withTiming,
  debugTime,
  debugTimeEnd,
  debugVerbose,
  strokeBrushRuntime,
  finalizeBrushRuntime,
  shapeBrushRuntime,
  playbackBrushRuntime,
  userBrushEngine,
  shapeRuntime,
  brushToolRuntime,
  colorCycleRuntime,
  feedbackMessageRef,
}: UseDrawingHandlersRuntimeSetupBridgeOptions): RuntimeBridgeArgs => ({
  refs,
  isPointerDownRef,
  strokeLifecycleOptions: buildDrawingHandlersStrokeLifecycleOptions({
    project,
    storeRef,
    sampleColorAt,
    debugVerbose,
    brushRuntime: strokeBrushRuntime,
    userBrushEngine,
    shapeRuntime,
    brushToolRuntime,
    colorCycleRuntime,
  }),
  finalizeRuntimeOptions: buildDrawingHandlersFinalizeRuntimeOptions({
    project,
    storeRef,
    isBusyRef,
    captureCanvasToActiveLayer,
    withTiming,
    debugTime,
    debugTimeEnd,
    debugVerbose,
    brushRuntime: finalizeBrushRuntime,
    userBrushEngine,
    brushToolRuntime,
    colorCycleRuntime,
  }),
  shapeLifecycleOptions: buildDrawingHandlersShapeLifecycleOptions({
    project,
    storeRef,
    sampleColorAt,
    isBusyRef,
    shapeMode,
    toolsRef,
    captureCanvasToActiveLayer,
    withTiming,
    debugTime,
    debugTimeEnd,
    shapeBrushRuntime,
    shapeRuntime,
    brushToolRuntime,
    colorCycleRuntime,
  }),
  playbackHandlersOptions: buildDrawingHandlersPlaybackHandlersOptions({
    project,
    storeRef,
    shapeMode,
    brushRuntime: playbackBrushRuntime,
    colorCycleRuntime,
    feedbackMessageRef,
  }),
});
