export const GOBLET_PROPERTY_MINIFY_MAP = {
  format: 'f',
  version: 'v',
  exportedAt: 'e',
  project: 'p',
  viewport: 'vp',
  container: 'c',
  animation: 'an',
  settings: 's',
  layers: 'l',
  gradients: 'grl',
  fallback: 'fb',
  schemaVersion: 'csv',
  id: 'i',
  name: 'n',
  type: 't',
  visible: 'vi',
  opacity: 'o',
  blendMode: 'bm',
  source: 'src',
  bounds: 'bnd',
  pixelBoundsPx: 'pbpx',
  pixelBoundsPercent: 'pbpr',
  documentBoundsPx: 'dbpx',
  documentBoundsPercent: 'dbpr',
  layoutPlacement: 'lp',
  frame: 'fr',
  transform: 'tr',
  anchor: 'anc',
  alignment: 'al',
  fit: 'ft',
  horizontal: 'hz',
  vertical: 'vt',
  positioning: 'ps',
  offsetPx: 'opx',
  offsetPercent: 'opc',
  contentBounds: 'cb',
  paintedSize: 'psz',
  assets: 'as',
  colorCycle: 'cc',
  stackIndex: 'si',
  width: 'w',
  height: 'h',
  x: 'x',
  y: 'y',
  designWidth: 'dw',
  designHeight: 'dh',
  texture: 'txr',
  textureFrames: 'txf',
  textureFrameMap: 'txfm',
  mode: 'md',
  isAnimating: 'ia',
  brushState: 'bs',
  alphaMask: 'amk',
  softEdgeMask: 'sem',
  gradientStops: 'gs',
  gradientIdBuffer: 'gib',
  gradientDefIdBuffer: 'gdib',
  indexBuffer: 'ib',
  speedBuffer: 'sbf',
  flowBuffer: 'flb',
  phaseBuffer: 'phb',
  slotPalettes: 'sp',
  gradientDefStore: 'gds',
  palette: 'pl',
  animationOffset: 'ao',
  targetFPS: 'tf',
  flowDirection: 'fd',
  alphaMode: 'am',
  recolorSettings: 'rs',
  gradient: 'gr',
  gradientRef: 'grf',
  brushSpeed: 'spd',
  layerBaseSpeedCps: 'lbsc',
  controllerSpeedCps: 'csc',
  legacySpeedCps: 'lsc',
  speedMode: 'smd',
  slotSpeeds: 'ss',
  speedMin: 'smin',
  speedMax: 'smax',
  bundleFormat: 'bf',
  viewportPreset: 'vpp',
  includeHiddenLayers: 'ihl',
  embedCanvasFallback: 'ecf',
  minifyOutput: 'mo',
  htmlTitle: 'htl',
  htmlBackgroundColor: 'hbc',
  transparencyBackgroundMode: 'tbm',
  perfectLoop: 'plp',
  fps: 'fps',
  totalFrames: 'tfm',
  durationSeconds: 'ds',
  phaseMap: 'pm',
  coverageBoundsPx: 'cbp',
  coverageBoundsSourcePx: 'cbsp',
  sequential: 'sq',
} as const;

export type GobletPropertyMinifyKey = keyof typeof GOBLET_PROPERTY_MINIFY_MAP;

export const invertGobletPropertyMinifyMap = (
  map: Record<string, string>
): Record<string, string> => {
  const inverted: Record<string, string> = {};
  for (const [key, value] of Object.entries(map)) {
    if (value in inverted) {
      throw new Error(`Duplicate Goblet minified property key "${value}" for "${key}" and "${inverted[value]}".`);
    }
    inverted[value] = key;
  }
  return inverted;
};

export const GOBLET_PROPERTY_UNMINIFY_MAP = invertGobletPropertyMinifyMap(
  GOBLET_PROPERTY_MINIFY_MAP
);
