// Generated from thomasareed/Classic-Mac-icons commit e976bf66ca181d6f14d7f120d3c665e2197a59d8.
// The upstream repository does not declare a licence; see THIRD_PARTY_NOTICES.md.

import type { UiShapeIconDefinition } from '@/utils/uiShapeIcons';

export const UI_SHAPE_MACINTOSH_ICONS: readonly UiShapeIconDefinition[] = [
  {
    'id': 'mac1-happy-mac',
    'label': 'System 1 · Happy Mac',
    'width': 32,
    'height': 32,
    'palette': [
      '#00000000',
      '#ffffffff',
      '#000000ff'
    ],
    'pixels': 'BQAVAgoAAQIVAQECCAABAhcBAQIHAAECAwERAgMBAQIHAAECAgEBAhEBAQICAQECBwABAgIBAQIRAQECAgEBAgcAAQICAQECEQEBAgIBAQIHAAECAgEBAgQBAQIDAQECAgEBAgUBAQICAQECBwABAgIBAQIEAQECAwEBAgIBAQIFAQECAgEBAgcAAQICAQECCAEBAggBAQICAQECBwABAgIBAQIIAQECCAEBAgIBAQIHAAECAgEBAgcBAgIIAQECAgEBAgcAAQICAQECEQEBAgIBAQIHAAECAgEBAgUBAQIEAQECBgEBAgIBAQIHAAECAgEBAgYBBAIHAQECAgEBAgcAAQICAQECEQEBAgIBAQIHAAECAgEBAhEBAQICAQECBwABAgMBEQIDAQECBwABAhcBAQIHAAECFwEBAgcAAQIXAQECBwABAhcBAQIHAAECDgEGAgMBAQIHAAECAgECAhMBAQIHAAECFwEBAgcAAQIXAQECBwABAhcBAQIIABcCCQABAhUBAQIJAAECFQEBAgkAAQIVAQECCQAXAgUA',
    'encoding': 'rle',
    'signature': {
      'lightness': 0.792143,
      'a': 0,
      'b': 0,
      'chroma': 0
    }
  },
  {
    'id': 'mac1-sad-mac',
    'label': 'System 1 · Sad Mac',
    'width': 32,
    'height': 32,
    'palette': [
      '#00000000',
      '#ffffffff',
      '#000000ff'
    ],
    'pixels': 'BQAVAgoAAQIVAQECCAABAhcBAQIHAAECAwERAgMBAQIHAAECAgEBAhEBAQICAQECBwABAgIBAQIRAQECAgEBAgcAAQICAQECAwEBAgEBAQIFAQECAQEBAgMBAQICAQECBwABAgIBAQIEAQECBwEBAgQBAQICAQECBwABAgIBAQIDAQECAQEBAgUBAQIBAQECAwEBAgIBAQIHAAECAgEBAhEBAQICAQECBwABAgIBAQIGAQECAgEBAgcBAQICAQECBwABAgIBAQIHAQICCAEBAgIBAQIHAAECAgEBAhEBAQICAQECBwABAgIBAQIGAQUCBgEBAgIBAQIHAAECAgEBAgUBAQIFAQICBAEBAgIBAQIHAAECAgEBAg0BAQIDAQECAgEBAgcAAQICAQECEQEBAgIBAQIHAAECAwERAgMBAQIHAAECFwEBAgcAAQIXAQECBwABAhcBAQIHAAECFwEBAgcAAQIOAQYCAwEBAgcAAQICAQICEwEBAgcAAQIXAQECBwABAhcBAQIHAAECFwEBAggAFwIJAAECFQEBAgkAAQIVAQECCQABAhUBAQIJABcCBQA=',
    'encoding': 'rle',
    'signature': {
      'lightness': 0.784958,
      'a': 0,
      'b': 0,
      'chroma': 0
    }
  },
  {
    'id': 'mac1-floppy',
    'label': 'System 1 · Floppy',
    'width': 32,
    'height': 32,
    'palette': [
      '#00000000',
      '#ffffffff',
      '#000000ff'
    ],
    'pixels': 'RAAXAggAAQIFAQECDQEBAgMBAQIHAAECBQEBAgcBAwIDAQECBAEBAgYAAQIFAQECBgEBAgMBAQICAQECBQEBAgUAAQIFAQECBgEBAgMBAQICAQECBQEBAgUAAQIFAQECBgEBAgMBAQICAQECBQEBAgUAAQIFAQECBgEBAgMBAQICAQECBQEBAgUAAQIFAQECBwEDAgMBAQIFAQECBQABAgUBAQINAQECBQEBAgUAAQIGAQ0CBgEBAgUAAQIZAQECBQABAhkBAQIFAAECGQEBAgUAAQIEARECBAEBAgUAAQIDAQECEQEBAgMBAQIFAAECAwEBAhEBAQIDAQECBQABAgMBAQIRAQECAwEBAgUAAQIDAQECEQEBAgMBAQIFAAECAwEBAhEBAQIDAQECBQABAgMBAQIRAQECAwEBAgUAAQIDAQECEQEBAgMBAQIFAAECAwEBAhEBAQIDAQECBQABAgMBAQIRAQECAwEBAgUAAQIDAQECEQEBAgMBAQIFAAECAwEBAhEBAQIDAQECBQABAgMBAQIRAQECAwEBAgYAGQJjAA==',
    'encoding': 'rle',
    'signature': {
      'lightness': 0.803219,
      'a': 0,
      'b': 0,
      'chroma': 0
    }
  },
  {
    'id': 'mac1-trash',
    'label': 'System 1 · Trash',
    'width': 32,
    'height': 32,
    'palette': [
      '#00000000',
      '#ffffffff',
      '#000000ff'
    ],
    'pixels': 'DgAFAhoAAQIFAAECEgAVAgoAAQIVAQECCQABAhUBAQIJABcCCgABAhMBAQILAAECEwEBAgsAAQIEAQECAwEBAgMBAQIDAQECAgEBAgsAAQIDAQECAwEBAgMBAQIDAQECAwEBAgsAAQIDAQECAwEBAgMBAQIDAQECAwEBAgsAAQIDAQECAwEBAgMBAQIDAQECAwEBAgsAAQIDAQECAwEBAgMBAQIDAQECAwEBAgsAAQIDAQECAwEBAgMBAQIDAQECAwEBAgsAAQIDAQECAwEBAgMBAQIDAQECAwEBAgsAAQIDAQECAwEBAgMBAQIDAQECAwEBAgsAAQIDAQECAwEBAgMBAQIDAQECAwEBAgsAAQIDAQECAwEBAgMBAQIDAQECAwEBAgsAAQIDAQECAwEBAgMBAQIDAQECAwEBAgsAAQIDAQECAwEBAgMBAQIDAQECAwEBAgsAAQIDAQECAwEBAgMBAQIDAQECAwEBAgsAAQIDAQECAwEBAgMBAQIDAQECAwEBAgsAAQIDAQECAwEBAgMBAQIDAQECAwEBAgsAAQIDAQECAwEBAgMBAQIDAQECAwEBAgsAAQIDAQECAwEBAgMBAQIDAQECAwEBAgsAAQIDAQECAwEBAgMBAQIDAQECAwEBAgsAAQIDAQECAwEBAgMBAQIDAQECAwEBAgsAAQIDAQECAwEBAgMBAQIDAQECAwEBAgsAAQIEAQECAwEBAgMBAQIDAQECAgEBAgsAAQITAQECCwABAhMBAQIMABMCBgA=',
    'encoding': 'rle',
    'signature': {
      'lightness': 0.745242,
      'a': 0,
      'b': 0,
      'chroma': 0
    }
  },
  {
    'id': 'mac1-text-file',
    'label': 'System 1 · Text File',
    'width': 32,
    'height': 32,
    'palette': [
      '#00000000',
      '#ffffffff',
      '#000000ff'
    ],
    'pixels': 'AwATAg0AAQIRAQICDAABAhEBAQIBAQECCwABAhEBAQICAQECCgABAhEBAQIDAQECCQABAgUBAwIBAQQCAQEEAgQBAQIIAAECEQEHAgcAAQIDAQMCAQEDAgEBBQIHAQECBwABAhcBAQIHAAECAwEFAgEBBgIBAQQCAwEBAgcAAQIXAQECBwABAgMBAwIBAQMCAQEDAgEBBAIEAQECBwABAhcBAQIHAAECFwEBAgcAAQIFAQQCAQEEAgEBBQIDAQECBwABAhcBAQIHAAECAwEEAgEBBAIBAQQCAQECAgMBAQIHAAECFwEBAgcAAQIDAQICAQEEAgEBBAIBAQQCAwEBAgcAAQIXAQECBwABAgMBBAIBAQUCAQEEAgUBAQIHAAECFwEBAgcAAQIXAQECBwABAgUBBAIBAQMCAQECAgEBAwIDAQECBwABAhcBAQIHAAECAwEEAgEBAwIBAQMCAQEEAgMBAQIHAAECFwEBAgcAAQIDAQMCAQEFAgEBBAIBAQICAwEBAgcAAQIXAQECBwABAhcBAQIHAAECFwEBAgcAGQIEAA==',
    'encoding': 'rle',
    'signature': {
      'lightness': 0.739769,
      'a': 0,
      'b': 0,
      'chroma': 0
    }
  },
  {
    'id': 'mac1-font-suitcase',
    'label': 'System 1 · Font Suitcase',
    'width': 32,
    'height': 32,
    'palette': [
      '#00000000',
      '#ffffffff',
      '#000000ff'
    ],
    'pixels': 'jgAGAhkAAQIGAQECDwAJAgEBBgIBAQoCBAABAggBAQIBAQECBAEBAgEBAQIIAQICAgABAgkBAwIEAQMCBwEBAgEBAQIBAAECGgEBAgIBAQIBABsCAwECAhoBAQIDAQICGgEBAgMBAgIQAQECCQEBAgMBAgIPAQICCQEBAgMBAgIOAQMCCQEBAgMBAgINAQECAQECAgkBAQIDAQICDAEBAgIBAgIJAQECAwECAgsBAQIDAQICCQEBAgMBAgIKAQECBAECAgkBAQIDAQICCQEIAgkBAQIDAQICCAEBAgYBAgIJAQECAwECAgcBAQIHAQICCQEBAgMBAgIGAQECCAECAgkBAQIDAQICBQEBAgkBAgIJAQECAwECAgMBBQIFAQYCBwEBAgIBAQIBAAECGgEBAgEBAQICAAECGgECAgQAGwJkAA==',
    'encoding': 'rle',
    'signature': {
      'lightness': 0.77752,
      'a': 0,
      'b': 0,
      'chroma': 0
    }
  },
  {
    'id': 'mac1-command',
    'label': 'System 1 · Command',
    'width': 32,
    'height': 32,
    'palette': [
      '#00000000',
      '#ffffffff',
      '#000000ff'
    ],
    'pixels': '/wArAAMCBAADAhUAAQIDAAECAgABAgMAAQIUAAECAwABAgIAAQIDAAECFAABAgMAAQICAAECAwABAhUACgIZAAECAgABAhwAAQICAAECGQAKAhUAAQIDAAECAgABAgMAAQIUAAECAwABAgIAAQIDAAECFAABAgMAAQICAAECAwABAhUAAwIEAAMC/wBtAA==',
    'encoding': 'rle',
    'signature': {
      'lightness': 0,
      'a': 0,
      'b': 0,
      'chroma': 0
    }
  },
  {
    'id': 'mac1-watch',
    'label': 'System 1 · Watch',
    'width': 32,
    'height': 32,
    'palette': [
      '#00000000',
      '#ffffffff',
      '#000000ff'
    ],
    'pixels': '/wAOAAYCGgAGAhoABgIaAAYCGQABAgYBAQIXAAECBAEBAgMBAQIWAAECBAEBAgMBAQIWAAECBAEBAgMBAgIVAAECAgEDAgMBAgIVAAECCAEBAhYAAQIIAQECFwABAgYBAQIZAAYCGgAGAhoABgIaAAYC/wAOAA==',
    'encoding': 'rle',
    'signature': {
      'lightness': 0.535755,
      'a': 0,
      'b': 0,
      'chroma': 0
    }
  },
  {
    'id': 'mac1-macpaint',
    'label': 'System 1 · MacPaint',
    'width': 32,
    'height': 32,
    'palette': [
      '#00000000',
      '#ffffffff',
      '#000000ff'
    ],
    'pixels': 'DwABAh4AAQIBAQECHAABAgMBAQIaAAECBQEBAhgAAQIFAQMCFgABAgUBBQIUAAECBQEHAhIAAQIFAQcCAQEBAhAAAQIGAQECAQEEAgMBAQIOAAECBgEBAgEBBAIFAQECDAABAgYBAQICAQMCBwEBAgoAAQIJAQECAQEBAgkBAQIIAAECCwEBAgsBAQIGAAECCwEBAg0BAQIEAAECEAEGAgUBAQICAAECCwEBAgQBAQIGAQECBQEBAgIAAQIJAQECBAEBAggBAQIFAQECAgABAgcBAgIDAQECAgECAgYBAQIDAQECBAABAgYBAwICAQMCAgEBAgYBAQIBAQECBgABAgYBBAICAQgCAwEEAgUAAQIIAQECAwECAgkBAwIGAAECCAEBAg0BAwIHAAECCAEBAgwBAwIIAAECCAECAgoBAwIJAAECCQEIAgIBAwIKAAECCwEBAgQABQILAAECCQEBAgcAAwIMAAECBwEBAhgAAQIFAQECGgABAgMBAQIcAAECAQEBAh4AAQIPAA==',
    'encoding': 'rle',
    'signature': {
      'lightness': 0.754739,
      'a': 0,
      'b': 0,
      'chroma': 0
    }
  },
  {
    'id': 'mac1-paint-brush',
    'label': 'System 1 · Paint Brush',
    'width': 32,
    'height': 32,
    'palette': [
      '#00000000',
      '#ffffffff',
      '#000000ff'
    ],
    'pixels': '/wAQAAMCHQABAgEBAQIdAAMCHQADAh0AAwIdAAMCHQADAhoACQIXAAECBwEBAhcACQIXAAECBwEBAhcAAQIHAQECFwABAgcBAQIXAAECAQEBAgEBAQIBAQECAQEBAhYAAQIBAQECAQEBAgEBAQIBAQICFQAKAv8ADQA=',
    'encoding': 'rle',
    'signature': {
      'lightness': 0.470193,
      'a': 0,
      'b': 0,
      'chroma': 0
    }
  },
];
