// Generated from thomasareed/Classic-Mac-icons commit e976bf66ca181d6f14d7f120d3c665e2197a59d8.
// The upstream repository does not declare a licence; see THIRD_PARTY_NOTICES.md.

import type { UiShapeIconDefinition } from '@/utils/uiShapeIcons';

export const UI_SHAPE_MACINTOSH_ICONS: readonly UiShapeIconDefinition[] = [
  {
    'id': 'mac1-about-mac',
    'label': 'Classic Mac · About Mac',
    'width': 32,
    'height': 32,
    'palette': [
      '#00000000',
      '#000000ff'
    ],
    'pixels': 'DQAMARMAAQEfAAEBBAAGAQMAAQERAAEBCgABAQIAAQERAAEBCgABAQIAAQEKAAEBBgABAQoAAQECAAEBCQACAQYAAQEKAAEBAgABAQkAAQEHAAEBCgABAQIAAQEGAAIBAgACAQUAAQEKAAEBAgABAQUAAQECAAIBAgABAQQAAQEKAAEBAgABAQUAAQEGAAEBBAABAQMABwEDAAEBBQABAQsAAQENAAEBBQABAQsAAQENAAEBBgABAQIAAQEBAAEBDAAFAQIAAQEHAAIBAQABARQAAQENAAYBDAABAQsAAgEdAAEBCQANAQkAAQEWAAEBCQAFAQgACAECAAEBDQABAQkAAQEBAAEBAQABAQEAAQECAAEBDAABAQwAAQEBAAEBAQABAQIAAQEKAAEBFAABAQoAAQEMAAgBDAACASAAAQEiAAIBHQABAQIAAQEbAAEBAgABAQEAAQEcAAEBAwABAR8AAQEeAAEBDAA=',
    'encoding': 'rle',
    'signature': {
      'lightness': 0,
      'a': 0,
      'b': 0,
      'chroma': 0
    }
  },
  {
    'id': 'mac1-alert',
    'label': 'Classic Mac · Alert',
    'width': 32,
    'height': 32,
    'palette': [
      '#00000000',
      '#000000ff',
      '#ffffffff'
    ],
    'pixels': 'IQEJAhcBCQIXAQkCFwEJAhcBBAIBAQQCCAEHAggBBAIBAQQCBgELAgYBBAIBAQQCBQENAgUBCQIFAQ0CBQEJAgQBBgIDAQYCBAEJAgQBBgIDAQYCBAEJAgQBBgIDAQYCBAEJAgQBBgIDAQYCBAEJAgQBBgIDAQYCBAEJAgQBBgIDAQYCBAEJAgQBBgIDAQYCBAEJAgQBBgIDAQYCBAEJAgQBBgIDAQYCBAEJAgQBBgIDAQYCBAEJAgQBBgIDAQYCBAEFAggBDwIEAQcCBgEGAgMBBgIEAQcCBgEGAgMBBgIEAQcCBgEGAgMBBQIFAQcCBgEOAgUBBwIFAQ4CBgEEAgYBDgIIAQcCGQEHAhkBBwIZAQcCOAE=',
    'encoding': 'rle',
    'signature': {
      'lightness': 0.59481,
      'a': 0,
      'b': 0,
      'chroma': 0
    }
  },
  {
    'id': 'mac1-appleshare',
    'label': 'Classic Mac · AppleShare',
    'width': 32,
    'height': 32,
    'palette': [
      '#00000000',
      '#000000ff',
      '#ffffffff'
    ],
    'pixels': 'DwABAR4AAQEBAgEBAgAIARIAAQEDAgEBAQABAQYCAgEQAAEBBQICAQYCAQEBAgEBDgABAQcCAQEGAgQBBwAEAQEAAQEJAgEBCAIBAQUAAgEEAggBBAIBAQcCAQEFAAEBDAIBAQUCAQEGAgEBBQABAQwCAQEGAgEBBQIBAQUAAQEMAgEBBQIBAQYCAQEFAAEBDAIBAQQCAQEHAgEBBQABAQwCAQEDAgEBCAIBAQUAAQEMAgEBAgIBAQkCAQEFAAEBDAIBAQECAgEJAgEBBQABAQwCAgEBAgEBCQIBAQIAIAEBAAEBHAIBAQMAHAEJAAEBAgIBAQECAQEBAgEBBgIBAQECAQEQAAEBAQIBAQECAQEBAgEBBgIBAQECAQEQAAEBAQIBAQECAQEBAgIBBQIBAQECAQERAAIBAgIBAQECAwEBAgMBAQIBARIAAQEDAgEBAwICAQECAwETAAIBAgIBAQQCAQECAgEBFAACAQcCAQEBAgEBFgACAQYCAgEYAAIBBQIBARoAAQEEAgEBGgABAQQCAQEZAAgBGAAIARgACAEHAA==',
    'encoding': 'rle',
    'signature': {
      'lightness': 0.695091,
      'a': 0,
      'b': 0,
      'chroma': 0
    }
  },
  {
    'id': 'mac1-bomb',
    'label': 'Classic Mac · Bomb',
    'width': 32,
    'height': 32,
    'palette': [
      '#00000000',
      '#000000ff',
      '#ffffffff'
    ],
    'pixels': 'NwABAQQAAQEeAAEBGAABAQMAAQEdAAEBFgAFAQoAAQEBAAEBDQABAQUAAgEDAAMBEQABAQgAAwEUAAEBEAABAQ4AAQEKAAEBAgABAQMAAQEKAAcBBgABARIABwEKAAEBDgAHARcACwETAA8BEQAPARAAEQEPABEBDgAEAQECDgENABMBDQADAQECDwENAAMBAQIPAQ0AAwEBAg8BDQATAQ0ABAEBAg4BDgARAQ8ABQEBAgsBEAAPAREADwETAAsBFwAHATEA',
    'encoding': 'rle',
    'signature': {
      'lightness': 0.110736,
      'a': 0,
      'b': 0,
      'chroma': 0
    }
  },
  {
    'id': 'mac1-chooser',
    'label': 'Classic Mac · Chooser',
    'width': 32,
    'height': 32,
    'palette': [
      '#00000000',
      '#000000ff',
      '#ffffffff'
    ],
    'pixels': 'aQAOARIAAQEMAgMBDQAEAQMCBQEEAgEBAQIFAQgAAQEDAgEBAwIBAQMCAQEEAgEBAgIBAQMCAQEEAAQBAwIBAQMCAQEDAgEBBAIBAQICAQEDAgEBAwABAQMCAQEDAgEBAwIBAQMCAQEEAgEBAgIBAQMCAQECAAEBAgIDAQMCAQECAgcBAwIBAQICAQEDAgEBAgABAQECAQECAAEBAwIBAQICAQEFAgIBAgIBAQICAQEDAgEBAgABAQECAQEDAAQBAgIHAQMCAQEBAgUBAwABAQECAQEGAAEBDAIDAQcAAQEBAgEBBgAOAQkAAQEBAgEBHQABAQECAQE9AAEBAQABAQgADgESAAEBDAIDAQ0ABAEHAgEBBAIBAQECBQEIAAEBAwIBAQICBwEDAgEBAgIBAQMCAQEEAAQBAwIBAQcCAQEEAgEBAgIBAQMCAQEDAAEBAwIBAQMCAQEMAgEBAgIBAQMCAQECAAEBAgIDAQMCAQEDAgEBCAIBAQICAQEDAgEBAgABAQECAQECAAEBAwIBAQICBwEDAgEBAgIBAQMCAQECAAEBAQIBAQMABAEDAgEBCAIBAQECBQEDAAEBAQIBAQYAAQEMAgMBBwABAQECAQEGAA4BCQABAQECAQEdAAEBAQIBAT0AAQEBAAEBGwA=',
    'encoding': 'rle',
    'signature': {
      'lightness': 0.619398,
      'a': 0,
      'b': 0,
      'chroma': 0
    }
  },
  {
    'id': 'mac1-classic-mac',
    'label': 'Classic Mac · Classic Mac',
    'width': 32,
    'height': 32,
    'palette': [
      '#00000000',
      '#000000ff',
      '#ffffffff'
    ],
    'pixels': 'JQAWAQkAAQEWAgEBCAABARYCAQEIAAEBAwIQAQMCAQEIAAEBAgIBARACAQECAgEBCAABAQICAQEBAgEBAQIBAQECAQEBAgEBAQIBAQECAQEEAgEBAgIBAQgAAQECAgEBEAIBAQICAQEIAAEBAgIBAQECAQEBAgEBAQIBAQECAQEIAgEBAgIBAQgAAQECAgEBEAIBAQICAQEIAAEBAgIBAQECAQEBAgEBDAIBAQICAQEIAAEBAgIBARACAQECAgEBCAABAQICAQEBAgEBAQIBAQwCAQECAgEBCAABAQICAQEQAgEBAgIBAQgAAQECAgEBAQIBAQECAQEBAgEBCgIBAQICAQEIAAEBAgIBARACAQECAgEBCAABAQICAQEQAgEBAgIBAQgAAQEDAhABAwIBAQgAAQEWAgEBCAABARYCAQEIAAEBFgIBAQgAAQEWAgEBCAABAQsCCAEDAgEBCAABARYCAQEIAAEBFgIBAQgAAQEWAgEBCAABARYCAQEJABYBCgABARQCAQEKAAEBFAIBAQoAAQEUAgEBCgAWAQUA',
    'encoding': 'rle',
    'signature': {
      'lightness': 0.783498,
      'a': 0,
      'b': 0,
      'chroma': 0
    }
  },
  {
    'id': 'mac1-command',
    'label': 'Classic Mac · Command',
    'width': 32,
    'height': 32,
    'palette': [
      '#00000000',
      '#000000ff'
    ],
    'pixels': '/wArAAMBBAADARUAAQEDAAEBAgABAQMAAQEUAAEBAwABAQIAAQEDAAEBFAABAQMAAQECAAEBAwABARUACgEZAAEBAgABARwAAQECAAEBGQAKARUAAQEDAAEBAgABAQMAAQEUAAEBAwABAQIAAQEDAAEBFAABAQMAAQECAAEBAwABARUAAwEEAAMB/wBtAA==',
    'encoding': 'rle',
    'signature': {
      'lightness': 0,
      'a': 0,
      'b': 0,
      'chroma': 0
    }
  },
  {
    'id': 'mac1-dogcow',
    'label': 'Classic Mac · Dogcow',
    'width': 32,
    'height': 32,
    'palette': [
      '#00000000',
      '#000000ff',
      '#ffffffff'
    ],
    'pixels': 'qAABAR4AAQEBAgEBAQACARoAAQEBAgIBAQIBARkAAQEFAgEBGAABAQICAQECAgEBDwABAQgAAQEGAgEBDwACAQYAAQEIAgEBDQABAQECAQEHAAQBBQICAQoAAQECAgEBCwABAQYCCgEDAgEBCwABAQYCBwEFAgEBDQACAQUCBgEEAgEBDgADAQYCAwEFAgEBDgADAQ0CAQEPAAIBDgIBAQ8AAQEPAgEBDwABAQMCCAEEAgEBDwABAQICAQEIAAEBBAIBAQ4AAQECAgEBCQABAQMCAQEOAAEBAgIBAQoAAQECAgEBDgABAQICAQEKAAEBAgIBAQ0AAQECAgEBCgABAQICAQEOAAMBCwADAacA',
    'encoding': 'rle',
    'signature': {
      'lightness': 0.652508,
      'a': 0,
      'b': 0,
      'chroma': 0
    }
  },
  {
    'id': 'mac1-draw-file',
    'label': 'Classic Mac · Draw file',
    'width': 32,
    'height': 32,
    'palette': [
      '#00000000',
      '#000000ff',
      '#ffffffff'
    ],
    'pixels': 'AwATAQ0AAQERAgIBDAABARECAQEBAgEBCwABARECAQECAgEBCgABAQICAQEFAgEBBQIBAQICAQEDAgEBCQABARECAQEEAgEBCAABARECBwEHAAEBCAIHAQgCAQEHAAEBCAIBAQUCAQEIAgEBBwABAQgCAQEFAgEBCAIBAQcAAQECAgEBBQIBAQICBwECAgEBAgIBAQcAAQEIAgEBAgIBAQUCAQEFAgEBBwABAQgCAQECAgEBBQIBAQUCAQEHAAEBCAIEAQUCAQEFAgEBBwABAQsCAQEFAgEBBQIBAQcAAQELAgEBBQIBAQUCAQEHAAEBAgIBAQUCAQECAgcBAgIBAQICAQEHAAEBFwIBAQcAAQEXAgEBBwABARcCAQEHAAEBFwIBAQcAAQEXAgEBBwABAQICAQEEAgMBBAIBAQUCAQECAgEBBwABAQYCAQEDAgEBDAIBAQcAAQEFAgEBBQIBAQsCAQEHAAEBBQIBAQUCAQELAgEBBwABAQUCAQEFAgEBCwIBAQcAAQEGAgEBAwIBAQwCAQEHAAEBAgIBAQQCAwEEAgEBBQIBAQICAQEHAAEBFwIBAQcAAQEXAgEBBwAZAQQA',
    'encoding': 'rle',
    'signature': {
      'lightness': 0.814421,
      'a': 0,
      'b': 0,
      'chroma': 0
    }
  },
  {
    'id': 'mac1-finger',
    'label': 'Classic Mac · Finger',
    'width': 32,
    'height': 32,
    'palette': [
      '#00000000',
      '#000000ff',
      '#ffffffff'
    ],
    'pixels': 'zQACAR0AAQECAgEBHAABAQICAQEcAAEBAgIBARwAAQECAgEBHAABAQICAQEcAAEBAgIDARYAAwEBAAEBBQICARQAAQECAgIBBwICARMAAQECAgEBCQIBARIAAQECAgEBCQIBARMAAQELAgEBEwABAQsCAQETAAEBCwIBARQAAQEJAgEBFQABAQkCAQEWAAEBBwIBARgAAQEGAgEBGAABAQYCAQHrAA==',
    'encoding': 'rle',
    'signature': {
      'lightness': 0.770502,
      'a': 0,
      'b': 0,
      'chroma': 0
    }
  },
  {
    'id': 'mac1-floppy',
    'label': 'Classic Mac · Floppy',
    'width': 32,
    'height': 32,
    'palette': [
      '#00000000',
      '#000000ff',
      '#ffffffff'
    ],
    'pixels': 'RAAXAQgAAQEFAgEBDQIBAQMCAQEHAAEBBQIBAQcCAwEDAgEBBAIBAQYAAQEFAgEBBgIBAQMCAQECAgEBBQIBAQUAAQEFAgEBBgIBAQMCAQECAgEBBQIBAQUAAQEFAgEBBgIBAQMCAQECAgEBBQIBAQUAAQEFAgEBBgIBAQMCAQECAgEBBQIBAQUAAQEFAgEBBwIDAQMCAQEFAgEBBQABAQUCAQENAgEBBQIBAQUAAQEGAg0BBgIBAQUAAQEZAgEBBQABARkCAQEFAAEBGQIBAQUAAQEEAhEBBAIBAQUAAQEDAgEBEQIBAQMCAQEFAAEBAwIBARECAQEDAgEBBQABAQMCAQERAgEBAwIBAQUAAQEDAgEBEQIBAQMCAQEFAAEBAwIBARECAQEDAgEBBQABAQMCAQERAgEBAwIBAQUAAQEDAgEBEQIBAQMCAQEFAAEBAwIBARECAQEDAgEBBQABAQMCAQERAgEBAwIBAQUAAQEDAgEBEQIBAQMCAQEFAAEBAwIBARECAQEDAgEBBQABAQMCAQERAgEBAwIBAQYAGQFjAA==',
    'encoding': 'rle',
    'signature': {
      'lightness': 0.803219,
      'a': 0,
      'b': 0,
      'chroma': 0
    }
  },
  {
    'id': 'mac1-font-suitcase',
    'label': 'Classic Mac · Font suitcase',
    'width': 32,
    'height': 32,
    'palette': [
      '#00000000',
      '#000000ff',
      '#ffffffff'
    ],
    'pixels': 'jgAGARkAAQEGAgEBDwAJAQECBgEBAgoBBAABAQgCAQEBAgEBBAIBAQECAQEIAgIBAgABAQkCAwEEAgMBBwIBAQECAQEBAAEBGgIBAQICAQEBABsBAwICARoCAQEDAgIBGgIBAQMCAgEQAgEBCQIBAQMCAgEPAgIBCQIBAQMCAgEOAgMBCQIBAQMCAgENAgEBAQICAQkCAQEDAgIBDAIBAQICAgEJAgEBAwICAQsCAQEDAgIBCQIBAQMCAgEKAgEBBAICAQkCAQEDAgIBCQIIAQkCAQEDAgIBCAIBAQYCAgEJAgEBAwICAQcCAQEHAgIBCQIBAQMCAgEGAgEBCAICAQkCAQEDAgIBBQIBAQkCAgEJAgEBAwICAQMCBQEFAgYBBwIBAQICAQEBAAEBGgIBAQECAQECAAEBGgICAQQAGwFkAA==',
    'encoding': 'rle',
    'signature': {
      'lightness': 0.77752,
      'a': 0,
      'b': 0,
      'chroma': 0
    }
  },
  {
    'id': 'mac1-hand',
    'label': 'Classic Mac · Hand',
    'width': 32,
    'height': 32,
    'palette': [
      '#00000000',
      '#000000ff',
      '#ffffffff'
    ],
    'pixels': '/wAQAAIBGgACAQEAAQECAgMBFgABAQICAgECAgEBAgIBARUAAQECAgIBAgIBAQICAQEBAAEBFAABAQICAQECAgEBAgICAQECAQETAAEBAgIBAQICAQECAgEBAgIBAREAAgEBAAEBBwIBAQICAQEQAAEBAgICAQoCAQEQAAEBAwIBAQkCAQESAAEBDAIBARMAAQELAgEBEwABAQoCAQEVAAEBCQIBARYAAQEHAgEBGAABAQYCAQEYAAEBBgIBAf8ADAA=',
    'encoding': 'rle',
    'signature': {
      'lightness': 0.75473,
      'a': 0,
      'b': 0,
      'chroma': 0
    }
  },
  {
    'id': 'mac1-happy-mac',
    'label': 'Classic Mac · Happy Mac',
    'width': 32,
    'height': 32,
    'palette': [
      '#00000000',
      '#000000ff',
      '#ffffffff'
    ],
    'pixels': 'BQAVAQoAAQEVAgEBCAABARcCAQEHAAEBAwIRAQMCAQEHAAEBAgIBARECAQECAgEBBwABAQICAQERAgEBAgIBAQcAAQECAgEBEQIBAQICAQEHAAEBAgIBAQQCAQEDAgEBAgIBAQUCAQECAgEBBwABAQICAQEEAgEBAwIBAQICAQEFAgEBAgIBAQcAAQECAgEBCAIBAQgCAQECAgEBBwABAQICAQEIAgEBCAIBAQICAQEHAAEBAgIBAQcCAgEIAgEBAgIBAQcAAQECAgEBEQIBAQICAQEHAAEBAgIBAQUCAQEEAgEBBgIBAQICAQEHAAEBAgIBAQYCBAEHAgEBAgIBAQcAAQECAgEBEQIBAQICAQEHAAEBAgIBARECAQECAgEBBwABAQMCEQEDAgEBBwABARcCAQEHAAEBFwIBAQcAAQEXAgEBBwABARcCAQEHAAEBDgIGAQMCAQEHAAEBAgICARMCAQEHAAEBFwIBAQcAAQEXAgEBBwABARcCAQEIABcBCQABARUCAQEJAAEBFQIBAQkAAQEVAgEBCQAXAQUA',
    'encoding': 'rle',
    'signature': {
      'lightness': 0.792143,
      'a': 0,
      'b': 0,
      'chroma': 0
    }
  },
  {
    'id': 'mac1-info',
    'label': 'Classic Mac · Info',
    'width': 32,
    'height': 32,
    'palette': [
      '#00000000',
      '#000000ff',
      '#ffffffff'
    ],
    'pixels': 'IQEIAhgBCAIYAQgCGAEIAhgBCAIJAQYCCQEDAgEBBAIHAQoCBwEDAgEBBAIGAQwCBgEDAgEBBAIFAQ4CBQEIAgQBEAIEAQgCBAEQAgQBCAIDARICAwEIAgMBAwIDAQECAwEBAgMBBAIDAQgCAwESAgMBCAIDARICAwEIAgMBAwIDAQECAwEBAgEBAQIBAQQCAwEIAgMBEgIDAQgCAwESAgMBCAIDAQMCAwEBAgEBAQIDAQYCAwEIAgMBEgIDAQQCBwESAgMBBgIFAQMCBAEBAgMBAQICAQQCAwEGAgUBEQIEAQYCBQERAgQBBgIFARACBQEGAgQBEAIGAQMCBQEQAggBBgIaAQYCGgEGAhoBBgI5AQ==',
    'encoding': 'rle',
    'signature': {
      'lightness': 0.614127,
      'a': 0,
      'b': 0,
      'chroma': 0
    }
  },
  {
    'id': 'mac1-lasso',
    'label': 'Classic Mac · Lasso',
    'width': 32,
    'height': 32,
    'palette': [
      '#00000000',
      '#000000ff'
    ],
    'pixels': '/wAvAAcBFgADAQcAAgETAAEBDAABAREAAQENAAEBEAABAQ4AAQEQAAEBDAACAREAAQEJAAMBFAADAQMAAwEWAAIBAgADARkAAQEBAAEBAQABARwAAwEfAAEBHwABAR4AAQH/ADYA',
    'encoding': 'rle',
    'signature': {
      'lightness': 0,
      'a': 0,
      'b': 0,
      'chroma': 0
    }
  },
  {
    'id': 'mac1-macdraw',
    'label': 'Classic Mac · MacDraw',
    'width': 32,
    'height': 32,
    'palette': [
      '#00000000',
      '#000000ff',
      '#ffffffff'
    ],
    'pixels': 'DwABAR4AAQEBAgEBHAABAQMCAQEaAAEBAgIBAQICAQEYAAEBBwIBARYAAQECAgEBAwIBAQICAQEUAAEBAgIBAQECAQEBAgEBAQIBAQICAQESAAEBAgIBAQMCAQEDAgEBAgIBARAAAQECAgEBAwIBAQUCAQECAgEBDgABAQICAQEDAgEBBwIBAQICAQEMAAEBBAIBAQMCAQEFAgEBBAIBAQoAAQECAgEBAwIBAQMCAQEDAgEBAwIBAQICAQEIAAEBCAIBAQECAQEBAgEBAQIBAQgCAQEGAAEBCgIBAQMCAQEKAgEBBAABARACBgEFAgEBAgABAQICAQEHAgEBBQIBAQYCAQECAgEBAgIBAQIAAQEOAgEBCAIBAQUCAQECAAEBDAIBAQICAgEGAgEBAwIBAQQAAQEKAgQBAgIBAQYCAQEBAgEBBgABAQICAQEDAg0BBAIEAQUAAQEEAgEBAwIBAQMCAgEJAgMBBgABAQMCAQEEAgEBDQIDAQcAAQECAgEBBQIBAQwCAwEIAAEBAgIBAQMCAQEBAgIBCgIDAQkAAQECAgMBBAIIAQICAwEKAAEBCwIBAQQABQELAAEBCQIBAQcAAwEMAAEBAgIBAQQCAQEYAAEBBQIBARoAAQEDAgEBHAABAQECAQEeAAEBDwA=',
    'encoding': 'rle',
    'signature': {
      'lightness': 0.753267,
      'a': 0,
      'b': 0,
      'chroma': 0
    }
  },
  {
    'id': 'mac1-macpaint',
    'label': 'Classic Mac · MacPaint',
    'width': 32,
    'height': 32,
    'palette': [
      '#00000000',
      '#000000ff',
      '#ffffffff'
    ],
    'pixels': 'DwABAR4AAQEBAgEBHAABAQMCAQEaAAEBBQIBARgAAQEFAgMBFgABAQUCBQEUAAEBBQIHARIAAQEFAgcBAQIBARAAAQEGAgEBAQIEAQMCAQEOAAEBBgIBAQECBAEFAgEBDAABAQYCAQECAgMBBwIBAQoAAQEJAgEBAQIBAQkCAQEIAAEBCwIBAQsCAQEGAAEBCwIBAQ0CAQEEAAEBEAIGAQUCAQECAAEBCwIBAQQCAQEGAgEBBQIBAQIAAQEJAgEBBAIBAQgCAQEFAgEBAgABAQcCAgEDAgEBAgICAQYCAQEDAgEBBAABAQYCAwECAgMBAgIBAQYCAQEBAgEBBgABAQYCBAECAggBAwIEAQUAAQEIAgEBAwICAQkCAwEGAAEBCAIBAQ0CAwEHAAEBCAIBAQwCAwEIAAEBCAICAQoCAwEJAAEBCQIIAQICAwEKAAEBCwIBAQQABQELAAEBCQIBAQcAAwEMAAEBBwIBARgAAQEFAgEBGgABAQMCAQEcAAEBAQIBAR4AAQEPAA==',
    'encoding': 'rle',
    'signature': {
      'lightness': 0.754739,
      'a': 0,
      'b': 0,
      'chroma': 0
    }
  },
  {
    'id': 'mac1-paint-brush',
    'label': 'Classic Mac · Paint brush',
    'width': 32,
    'height': 32,
    'palette': [
      '#00000000',
      '#000000ff',
      '#ffffffff'
    ],
    'pixels': '/wAQAAMBHQABAQECAQEdAAMBHQADAR0AAwEdAAMBHQADARoACQEXAAEBBwIBARcACQEXAAEBBwIBARcAAQEHAgEBFwABAQcCAQEXAAEBAQIBAQECAQEBAgEBAQIBARYAAQEBAgEBAQIBAQECAQEBAgIBFQAKAf8ADQA=',
    'encoding': 'rle',
    'signature': {
      'lightness': 0.470193,
      'a': 0,
      'b': 0,
      'chroma': 0
    }
  },
  {
    'id': 'mac1-paint-bucket',
    'label': 'Classic Mac · Paint Bucket',
    'width': 32,
    'height': 32,
    'palette': [
      '#00000000',
      '#000000ff',
      '#ffffffff'
    ],
    'pixels': '7QADARwAAQEDAAEBGwABAQIAAgEbAAEBAQABAQECAgEaAAIBAgIBAQECAgEYAAEBAwIBAQICAwEVAAEBBAIBAQMCAwETAAEBBAIBAQECAQEDAgMBEQABAQYCAQEEAgMBEAABAQsCBAEQAAEBCgIBAQEAAwERAAEBCAIBAQIAAwESAAEBBgIBAQMAAwETAAEBBAIBAQQAAwEUAAEBAgIBAQUAAgEWAAIBBgABAf8AKwA=',
    'encoding': 'rle',
    'signature': {
      'lightness': 0.613001,
      'a': 0,
      'b': 0,
      'chroma': 0
    }
  },
  {
    'id': 'mac1-paint-file',
    'label': 'Classic Mac · Paint file',
    'width': 32,
    'height': 32,
    'palette': [
      '#00000000',
      '#000000ff',
      '#ffffffff'
    ],
    'pixels': 'AwATAQ0AAQERAgIBDAABAQICAwEBAgEBCgIBAQECAQELAAEBAgIDAQECAQEKAgEBAgIBAQoAAQECAgMBAQIBAQoCAQEDAgEBCQABAQICAwEBAgEBCgIBAQQCAQEIAAEBAgIDAQECAQEKAgcBBwABAQICAwEBAgEBEAIBAQcAAQECAgMBAQIBARACAQEHAAEBAgIDAQECAQEQAgEBBwABAQICAwEBAgEBEAIBAQcAAQECAgMBAQIBARACAQEHAAEBAgIFARACAQEHAAEBAgIBAQMCAQEQAgEBBwABAQICAQEDAgEBEAIBAQcAAQECAgEBAwIBARACAQEHAAEBAgIBAQMCAQEQAgEBBwABAQICAQEDAgEBEAIBAQcAAQEDAgMBEQIBAQcAAQECAgUBEAIBAQcAAQECAgUBEAIBAQcAAQECAgYBDwIBAQcAAQECAgYBDwIBAQcAAQECAgQBAQIBAQQCAQEBAggBAQIBAQcAAQECAgYBBwIBAQECBQEBAgEBBwABAQMCAgEBAgEBBgIJAQECAQEHAAEBAwIEAQQCCwEBAgEBBwABAQQCAwEGAgkBAQIBAQcAAQEGAgIBAgIMAQECAQEHAAEBFwIBAQcAAQEXAgEBBwAZAQQA',
    'encoding': 'rle',
    'signature': {
      'lightness': 0.722927,
      'a': 0,
      'b': 0,
      'chroma': 0
    }
  },
  {
    'id': 'mac1-pencil',
    'label': 'Classic Mac · Pencil',
    'width': 32,
    'height': 32,
    'palette': [
      '#00000000',
      '#000000ff',
      '#ffffffff'
    ],
    'pixels': '/wARAAQBHAABAQMCAQEaAAEBBAIBARoAAgECAgEBGgABAQICAwEaAAEBAwIBARoAAQEEAgEBGgABAQMCAQEaAAEBBAIBARoAAQEDAgEBGgABAQQCAQEaAAEBAwIBARsABAEcAAMBHQACAR4AAQH/ABUA',
    'encoding': 'rle',
    'signature': {
      'lightness': 0.574761,
      'a': 0,
      'b': 0,
      'chroma': 0
    }
  },
  {
    'id': 'mac1-sad-mac',
    'label': 'Classic Mac · Sad Mac',
    'width': 32,
    'height': 32,
    'palette': [
      '#00000000',
      '#000000ff',
      '#ffffffff'
    ],
    'pixels': 'BQAVAQoAAQEVAgEBCAABARcCAQEHAAEBAwIRAQMCAQEHAAEBAgIBARECAQECAgEBBwABAQICAQERAgEBAgIBAQcAAQECAgEBAwIBAQECAQEFAgEBAQIBAQMCAQECAgEBBwABAQICAQEEAgEBBwIBAQQCAQECAgEBBwABAQICAQEDAgEBAQIBAQUCAQEBAgEBAwIBAQICAQEHAAEBAgIBARECAQECAgEBBwABAQICAQEGAgEBAgIBAQcCAQECAgEBBwABAQICAQEHAgIBCAIBAQICAQEHAAEBAgIBARECAQECAgEBBwABAQICAQEGAgUBBgIBAQICAQEHAAEBAgIBAQUCAQEFAgIBBAIBAQICAQEHAAEBAgIBAQ0CAQEDAgEBAgIBAQcAAQECAgEBEQIBAQICAQEHAAEBAwIRAQMCAQEHAAEBFwIBAQcAAQEXAgEBBwABARcCAQEHAAEBFwIBAQcAAQEOAgYBAwIBAQcAAQECAgIBEwIBAQcAAQEXAgEBBwABARcCAQEHAAEBFwIBAQgAFwEJAAEBFQIBAQkAAQEVAgEBCQABARUCAQEJABcBBQA=',
    'encoding': 'rle',
    'signature': {
      'lightness': 0.784958,
      'a': 0,
      'b': 0,
      'chroma': 0
    }
  },
  {
    'id': 'mac1-simpletext',
    'label': 'Classic Mac · SimpleText',
    'width': 32,
    'height': 32,
    'palette': [
      '#00000000',
      '#000000ff',
      '#ffffffff'
    ],
    'pixels': 'DwABAR4AAQEBAgEBHAABAQMCAQEaAAEBBQIBARgAAQEHAgEBFgABAQMCAQEFAgEBFAABAQMCAQECAgEBBAIBARIAAQEDAgEBAgIBAQYCAQEQAAEBCQIBAQUCAQEOAAEBAwIBAQICAQECAgEBAgIBAQQCAQEMAAEBAwIBAQICAQEFAgEBBgIBAQoAAQEJAgEBAgIBAQgCAQEIAAEBAwIBAQICAQECAgEBAgIBAQoCAQEGAAEBAwIBAQICAQECAgEBAgIBAQwCAQEEAAEBAwIBAQICAQEJAgYBBQIBAQIAAQEGAgEBAgIBAQICAQEDAgEBBgIBAQUCAQECAAEBBAIBAQICAQECAgEBAwIBAQgCAQEFAgEBAgABAQUCAQECAgEBAwIBAQICAgEGAgEBAwIBAQQAAQEDAgEBAgIBAQQCAwECAgEBBgIBAQECAQEGAAEBBAIBAQICAwECAggBAwIEAQUAAQEFAgEBAgIBAQMCAgEJAgMBBgABAQMCAQEEAgEBDQIDAQcAAQEIAgEBDAIDAQgAAQEIAgIBCgIDAQkAAQEJAggBAgIDAQoAAQELAgEBBAAFAQsAAQEJAgEBBwADAQwAAQEHAgEBGAABAQUCAQEaAAEBAwIBARwAAQEBAgEBHgABAQ8A',
    'encoding': 'rle',
    'signature': {
      'lightness': 0.765019,
      'a': 0,
      'b': 0,
      'chroma': 0
    }
  },
  {
    'id': 'mac1-sound',
    'label': 'Classic Mac · Sound',
    'width': 32,
    'height': 32,
    'palette': [
      '#00000000',
      '#000000ff',
      '#ffffffff'
    ],
    'pixels': '7wABAR4AAgEdAAMBBwABARQAAgEBAgEBBAABAQMAAQEOAAYBAQICAQUAAQECAAEBDgACAQQCAwECAAEBAwABAQIAAQENAAkBAwABAQIAAQECAAEBDQAJAQMAAQECAAEBAgABAQ0ACQEDAAEBAgABAQIAAQENAAkBAwABAQIAAQECAAEBDQAJAQIAAQEDAAEBAgABAQ0ACQEFAAEBAgABARMABAEEAAEBAwABARQAAwEHAAEBFgACAR8AAQH/ADEA',
    'encoding': 'rle',
    'signature': {
      'lightness': 0.157888,
      'a': 0,
      'b': 0,
      'chroma': 0
    }
  },
  {
    'id': 'mac1-spray-can',
    'label': 'Classic Mac · Spray Can',
    'width': 32,
    'height': 32,
    'palette': [
      '#00000000',
      '#000000ff',
      '#ffffffff'
    ],
    'pixels': '/wALAAEBIQABAR0AAQEDAAEBAQABAQEAAQEZAAEBBAADARYAAQEFAAEBAwIBARoABwEZAAEBBQIBARkAAQECAgQBGQABAQICAQECAgEBGQABAQICBAEZAAEBAgIBAQICAQEZAAEBAgIEARkAAQECAgQBGQABAQUCAQEZAAEBBQIBARkABwH/AAsA',
    'encoding': 'rle',
    'signature': {
      'lightness': 0.479166,
      'a': 0,
      'b': 0,
      'chroma': 0
    }
  },
  {
    'id': 'mac1-stop',
    'label': 'Classic Mac · Stop',
    'width': 32,
    'height': 32,
    'palette': [
      '#00000000',
      '#000000ff',
      '#ffffffff'
    ],
    'pixels': 'CAAQAQ8AEgENABQBCwAKAQECCwEJAAoBAwILAQcACAEBAgIBAwICAQICCAEFAAgBAwIBAQMCAQEDAgkBAwAJAQMCAQEDAgEBAwIKAQEACAEBAgEBAwIBAQMCAQEDAhIBAgIBAQMCAQEDAgEBAwISAQICAQEDAgEBAwIBAQMCEgECAgEBAwIBAQMCAQEDAhIBAgIBAQMCAQEDAgEBAwISAQICAQEDAgEBAwIBAQMCEgECAgEBCwIDAQMCDAEOAgIBBAIMAQ4CAgEEAgwBDgIBAQQCDQETAg0BEgIOARICDgERAg8BEQIPARACEAEQAgkBAQAGAQYCAQEIAgkBAwAGAQYCAQEGAgkBBQAaAQcAGAEJABYBCwAUAQ0AEgEHAA==',
    'encoding': 'rle',
    'signature': {
      'lightness': 0.461209,
      'a': 0,
      'b': 0,
      'chroma': 0
    }
  },
  {
    'id': 'mac1-stylewriter',
    'label': 'Classic Mac · StyleWriter',
    'width': 32,
    'height': 32,
    'palette': [
      '#00000000',
      '#000000ff',
      '#ffffffff'
    ],
    'pixels': 'JQANARMAAQELAgIBEgABAQECAQEJAgEBAQIBAREAAQELAgEBAgIBARAAAQEBAgEBCQIBAQMCAQEPAAEBCwIBAQQCAQEOAAEBAQIBAQkCBwENAAEBEQIBAQ0AAQEBAgEBDQIBAQECAQENAAEBEQIBAQ0AAQEBAgEBDQIBAQECAQENAAEBEQIBAQ0AAQEBAgEBDQIBAQECAQENAAEBEQIBAQ0AAQEBAgEBDQIBAQECAQENAAEBEQIBAQgAHQEDAAEBAgIBARUCAQECAgUBAgIXAQICAQECAgIBAgIBARUCAQECAgEBAgICAQICAQEVAgEBAgIBAQICAgECAgEBFQIBAQICBQECAhcBAgIBAQMAAQEbAgEBAwABARsCAQEDAAEBGwIBAQMAAQEbAgEBAwAdAQMAAQEbAgEBAwAdASMA',
    'encoding': 'rle',
    'signature': {
      'lightness': 0.735306,
      'a': 0,
      'b': 0,
      'chroma': 0
    }
  },
  {
    'id': 'mac1-text-file',
    'label': 'Classic Mac · Text file',
    'width': 32,
    'height': 32,
    'palette': [
      '#00000000',
      '#000000ff',
      '#ffffffff'
    ],
    'pixels': 'AwATAQ0AAQERAgIBDAABARECAQEBAgEBCwABARECAQECAgEBCgABARECAQEDAgEBCQABAQUCAwEBAgQBAQIEAQQCAQEIAAEBEQIHAQcAAQEDAgMBAQIDAQECBQEHAgEBBwABARcCAQEHAAEBAwIFAQECBgEBAgQBAwIBAQcAAQEXAgEBBwABAQMCAwEBAgMBAQIDAQECBAEEAgEBBwABARcCAQEHAAEBFwIBAQcAAQEFAgQBAQIEAQECBQEDAgEBBwABARcCAQEHAAEBAwIEAQECBAEBAgQBAQICAQMCAQEHAAEBFwIBAQcAAQEDAgIBAQIEAQECBAEBAgQBAwIBAQcAAQEXAgEBBwABAQMCBAEBAgUBAQIEAQUCAQEHAAEBFwIBAQcAAQEXAgEBBwABAQUCBAEBAgMBAQICAQECAwEDAgEBBwABARcCAQEHAAEBAwIEAQECAwEBAgMBAQIEAQMCAQEHAAEBFwIBAQcAAQEDAgMBAQIFAQECBAEBAgIBAwIBAQcAAQEXAgEBBwABARcCAQEHAAEBFwIBAQcAGQEEAA==',
    'encoding': 'rle',
    'signature': {
      'lightness': 0.739769,
      'a': 0,
      'b': 0,
      'chroma': 0
    }
  },
  {
    'id': 'mac1-trash-full',
    'label': 'Classic Mac · Trash — full',
    'width': 32,
    'height': 32,
    'palette': [
      '#00000000',
      '#000000ff',
      '#ffffffff'
    ],
    'pixels': 'DQAGARkAAQEGAAEBEgAUAQsAAQEUAgEBCgAWAQsAAQESAgEBDAABARICAQEMAAEBAwIBAQoCAQEDAgEBCwABAQMCAQEDAgEBBAIBAQMCAQEDAgEBCgABAQMCAQEDAgEBBAIBAQMCAQEDAgEBCQABAQMCAQEDAgEBBgIBAQMCAQEDAgEBCAABAQMCAQEDAgEBBgIBAQMCAQEDAgEBBwABAQMCAQEDAgEBCAIBAQMCAQEDAgEBBgABAQMCAQEDAgEBCAIBAQMCAQEDAgEBBgABAQMCAQEDAgEBCAIBAQMCAQEDAgEBBgABAQMCAQEDAgEBCAIBAQMCAQEDAgEBBgABAQMCAQEDAgEBCAIBAQMCAQEDAgEBBgABAQMCAQEDAgEBCAIBAQMCAQEDAgEBBgABAQMCAQEDAgEBCAIBAQMCAQEDAgEBBgABAQMCAQEDAgEBCAIBAQMCAQEDAgEBBgABAQMCAQEDAgEBCAIBAQMCAQEDAgEBBgABAQMCAQEDAgEBCAIBAQMCAQEDAgEBBgABAQMCAQEDAgEBCAIBAQMCAQEDAgEBBwABAQMCAQEDAgEBBgIBAQMCAQEDAgEBCAABAQMCAQEDAgEBBgIBAQMCAQEDAgEBCQABAQICAQEEAgEBBAIBAQQCAQECAgEBCgABAQMCAQEDAgEBBAIBAQMCAQEDAgEBCgABAQMCAQEDAgEBBAIBAQMCAQEDAgEBCwABAQMCAQEOAgEBDAABARICAQEMAAEBEgIBAQ0AEgEHAA==',
    'encoding': 'rle',
    'signature': {
      'lightness': 0.771627,
      'a': 0,
      'b': 0,
      'chroma': 0
    }
  },
  {
    'id': 'mac1-trash-fire',
    'label': 'Classic Mac · Trash fire',
    'width': 32,
    'height': 52,
    'palette': [
      '#00000000',
      '#000000ff',
      '#ffffffff'
    ],
    'pixels': 'DAABAQECAQEdAAEBAQIBAR0AAQEBAgEBHQABAQECAQEdAAEBAQICARwAAQECAgEBGwABAQMCAQEbAAEBAwICARoAAQEEAgEBGgABAQQCAgEZAAEBBQIBARkAAQEFAgEBGQABAQUCAQEZAAEBBQIBAQkAAQEOAAIBBgIBAQEAAQEFAAEBAQIBAQwAAQEIAgEBAQABAQUAAQEBAgEBCQABAQIAAQEGAgEBAgIBAQECAQEEAAEBAQIBAQgAAQEDAAEBBQIBAQECAQEDAgEBBQABAQgAAQEBAgEBAgABAQYCAQEEAgEBDgABAQECAQECAAEBCwIBAQ4AAQECAgIBDAIBAQ4AAQEEAgEBCwIBAQcAAQEGAAEBCQIFAQMCAQEFAAIBBgABAQgCAQEFAgEBAgIBAQQAAQEBAgEBBQABAQICFQECAgEBBQABAQECAQEVAgEBAQIBAQYAAgEVAgEBAQIBAQcAFwEBAgEBCAABARMCAQECAgEBCAABARMCAQECAgEBBAABAQMAAQEEAgEBAwIBAQMCAQEDAgEBAgIBAQECAgEEAAIBAgABAQMCAQEDAgEBAwIBAQMCAQEDAgEBAQIBAQUAAQEBAgEBAQABAQMCAQEDAgEBAwIBAQMCAQEDAgEBAQIBAQIAAQECAAEBAgICAQMCAQEDAgEBAwIBAQMCAQEDAgEBAQIBAQEAAgECAAEBAwIBAQMCAQEDAgEBAwIBAQMCAQEDAgEBAgIBAQECAQECAAEBAwIBAQMCAQEDAgEBAwIBAQMCAQEDAgEBBAIBAQIAAQEDAgEBAwIBAQMCAQEDAgEBAwIBAQMCAQEDAgEBAQABAQEAAQEDAgEBAwIBAQMCAQEDAgEBAwIBAQMCAQEDAgEBAQABAgEBBAIBAQMCAQEDAgEBAwIBAQMCAQEDAgEBAgIBAQIAAwIBAQICAQEDAgEBAwIBAQMCAQEDAgEBAwIBAQICAQECAAEBBQIBAQMCAQEDAgEBAwIBAQMCAQEDAgEBAgIBAQIAAQEFAgEBAwIBAQMCAQEDAgEBAwIBAQMCAQEDAgEBAQABAQUCAQEDAgEBAwIBAQMCAQEDAgEBAwIBAQICAQEBAgEBAQABAQQCAQEDAgEBAwIBAQMCAQEDAgEBAwIBAQUCAQACAQMCAQEDAgEBAwIBAQMCAQEDAgEBAwIBAQUCAQEBAAEBAwIBAQMCAQEDAgEBAwIBAQMCAQEDAgEBBAIBAQECAQEEAgEBAwIBAQMCAQEDAgEBAwIBAQMCAQEEAgEBBgIBAQMCAQEDAgEBAwIBAQMCAQEDAgEBAwIBAQEABgIBAQMCAQEDAgEBAwIBAQMCAQEDAgEBAgIBAQIAAQEFAgEBAwIBAQMCAQEDAgEBAwIBAQMCAQEBAgEBAwABAQUCAQEEAgEBAwIBAQMCAQEDAgEBAgIBAQECAQEEAAEBBAIBARMCAgEEAA==',
    'encoding': 'rle',
    'signature': {
      'lightness': 0.753361,
      'a': 0,
      'b': 0,
      'chroma': 0
    }
  },
  {
    'id': 'mac1-trash',
    'label': 'Classic Mac · Trash',
    'width': 32,
    'height': 32,
    'palette': [
      '#00000000',
      '#000000ff',
      '#ffffffff'
    ],
    'pixels': 'DgAFARoAAQEFAAEBEgAVAQoAAQEVAgEBCQABARUCAQEJABcBCgABARMCAQELAAEBEwIBAQsAAQEEAgEBAwIBAQMCAQEDAgEBAgIBAQsAAQEDAgEBAwIBAQMCAQEDAgEBAwIBAQsAAQEDAgEBAwIBAQMCAQEDAgEBAwIBAQsAAQEDAgEBAwIBAQMCAQEDAgEBAwIBAQsAAQEDAgEBAwIBAQMCAQEDAgEBAwIBAQsAAQEDAgEBAwIBAQMCAQEDAgEBAwIBAQsAAQEDAgEBAwIBAQMCAQEDAgEBAwIBAQsAAQEDAgEBAwIBAQMCAQEDAgEBAwIBAQsAAQEDAgEBAwIBAQMCAQEDAgEBAwIBAQsAAQEDAgEBAwIBAQMCAQEDAgEBAwIBAQsAAQEDAgEBAwIBAQMCAQEDAgEBAwIBAQsAAQEDAgEBAwIBAQMCAQEDAgEBAwIBAQsAAQEDAgEBAwIBAQMCAQEDAgEBAwIBAQsAAQEDAgEBAwIBAQMCAQEDAgEBAwIBAQsAAQEDAgEBAwIBAQMCAQEDAgEBAwIBAQsAAQEDAgEBAwIBAQMCAQEDAgEBAwIBAQsAAQEDAgEBAwIBAQMCAQEDAgEBAwIBAQsAAQEDAgEBAwIBAQMCAQEDAgEBAwIBAQsAAQEDAgEBAwIBAQMCAQEDAgEBAwIBAQsAAQEDAgEBAwIBAQMCAQEDAgEBAwIBAQsAAQEEAgEBAwIBAQMCAQEDAgEBAgIBAQsAAQETAgEBCwABARMCAQEMABMBBgA=',
    'encoding': 'rle',
    'signature': {
      'lightness': 0.745242,
      'a': 0,
      'b': 0,
      'chroma': 0
    }
  },
  {
    'id': 'mac1-warning',
    'label': 'Classic Mac · Warning',
    'width': 32,
    'height': 32,
    'palette': [
      '#00000000',
      '#000000ff',
      '#ffffffff'
    ],
    'pixels': 'DwACAR0ABAEcAAQBGwACAQICAgEaAAIBAgICARkAAgEEAgIBGAACAQQCAgEXAAIBBgICARYAAgECAgIBAgICARUAAgECAgQBAgICARQAAgECAgQBAgICARMAAgEDAgQBAwICARIAAgEDAgQBAwICAREAAgEEAgQBBAICARAAAgEEAgQBBAICAQ8AAgEFAgQBBQICAQ4AAgEFAgQBBQICAQ0AAgEGAgQBBgICAQwAAgEGAgQBBgICAQsAAgEHAgQBBwICAQoAAgEIAgIBCAICAQkAAgEJAgIBCQICAQgAAgEUAgIBBwACARYCAgEGAAIBCgICAQoCAgEFAAIBCgIEAQoCAgEEAAIBCgIEAQoCAgEDAAIBDAICAQwCAgECAAIBGgICAQEAAgEcAiIBAQAeAQEA',
    'encoding': 'rle',
    'signature': {
      'lightness': 0.663635,
      'a': 0,
      'b': 0,
      'chroma': 0
    }
  },
  {
    'id': 'mac1-watch',
    'label': 'Classic Mac · Watch',
    'width': 32,
    'height': 32,
    'palette': [
      '#00000000',
      '#000000ff',
      '#ffffffff'
    ],
    'pixels': '/wAOAAYBGgAGARoABgEaAAYBGQABAQYCAQEXAAEBBAIBAQMCAQEWAAEBBAIBAQMCAQEWAAEBBAIBAQMCAgEVAAEBAgIDAQMCAgEVAAEBCAIBARYAAQEIAgEBFwABAQYCAQEZAAYBGgAGARoABgEaAAYB/wAOAA==',
    'encoding': 'rle',
    'signature': {
      'lightness': 0.535755,
      'a': 0,
      'b': 0,
      'chroma': 0
    }
  },
];
