import { createDefaultLayerAlignment } from '@/utils/layoutDefaults';
import type { BrushSettings, Layer } from '@/types';
import { resolveActiveColorCycleGradient } from '@/hooks/canvas/utils/colorCycleHelpers';

const createBrushSettings = (): BrushSettings => ({
  size: 10,
  opacity: 1,
  color: '#000000',
  blendMode: 'source-over',
  spacing: 1,
  pressure: 1,
  rotation: 0,
  antialiasing: true,
  brushShape: 'color_cycle' as BrushSettings['brushShape'],
  selectedCustomBrush: null,
  customBrushSizePercent: 100,
  lastRegularBrushSize: 10,
  pressureEnabled: false,
  minPressure: 1,
  maxPressure: 1000,
  rotationEnabled: false,
  dashedEnabled: false,
  dashLength: 1,
  dashGap: 1,
  velocityAnimationSpeedEnabled: false,
  useSwatchColor: false,
  flow: 1,
  gridSnapEnabled: false,
  shapeEnabled: false,
  hueShift: 0,
  lightnessAdjust: 0,
  saturationAdjust: 0,
  colorJitter: 0,
  risographIntensity: 0,
  risographOutline: false,
  ditherEnabled: false,
  ditherPaletteSpread: 0,
  ditherPhaseJitter: 0,
  ditherAlgorithm: 'sierra-lite',
  patternStyle: 'dots',
  lostEdge: 0,
  fillResolution: 1,
  continuousSampling: false,
  resampleInterval: 5,
  autoSampleColor: false,
  colors: 2,
  rectGradientPresetId: 'none',
  polygonSampleColors: false,
  shapeFillMode: 'default',
  contourSpacing: 2,
  contourVariance: 0,
  contourSmoothness: 0,
  contourMaxDistance: 0,
  contourLines2Spacing: 2,
  contourLines2Density: 1,
  contourLines2Alternate: false,
  triangleFillSize: 16,
  triangleFillJitter: 0,
  triangleFillRotation: 0,
  crossHatchRotation: 0,
  crossHatchSpacing: 4,
  crossHatchLineWidth: 1,
  flowSeedSpacing: 8,
  flowStepSize: 1,
  flowMaxSteps: 10,
  flowUseOrthogonal: false,
  flowFieldResolution: 4,
  flowOrientationAngle: 0,
  flowSeedJitter: 0,
  ribbonSdfStep: 4,
  ribbonSeedSpacing: 8,
  ribbonStepSize: 1,
  ribbonMaxSteps: 10,
  ribbonTangentWeight: 0,
  ribbonBiasAngle: 0,
  ribbonNoiseStrength: 0,
  ribbonNoiseScale: 1,
  ribbonNoiseOctaves: 1,
  ribbonLineWidth: 1,
  ribbonJitter: 0,
  ribbonAnchorFalloff: 0,
  ribbonSeed: 1,
  colorCycleFlowMode: 'forward',
  customBrushColorCycle: false,
  colorCycleSpeed: 0.1,
  colorCycleLayerSpeedScale: 1,
  colorCycleStampShape: 'square',
  colorCycleStampDitherPressureLinked: false,
  colorCycleUseForegroundGradient: false,
  colorCycleFgLightness: 50,
  colorCycleFgVariance: 0,
  colorCycleFgHueShift: 0,
  colorCycleFgSaturationShift: 0,
  colorCycleFgStops: 2,
  colorCycleGradient: [
    { position: 0, color: '#000000' },
    { position: 1, color: '#ffffff' },
  ],
  colorCycleGradientVersion: 0,
  colorCycleFPS: 30,
  colorCycleFillMode: 'concentric',
  colorCycleBandSpacingPx: 12,
  autoSampleGradient: false,
  gradientBands: 12,
  polygonSides: 3,
  polygonDitherResolution: 1,
  spamFont: 'default',
  spamContentType: 'default',
  spamCustomText: '',
  shapeGradientMode: 'contour',
  linkSizeToBrush: true,
});

const createLayer = (): Layer =>
  ({
    id: 'layer-cc',
    name: 'CC Layer',
    visible: true,
    opacity: 1,
    blendMode: 'source-over',
    locked: false,
    transparencyLocked: false,
    order: 0,
    imageData: null,
    framebuffer: document.createElement('canvas'),
    alignment: createDefaultLayerAlignment(),
    layerType: 'color-cycle',
    colorCycleData: {
      gradient: [],
      gradientDefs: [{ id: 'g0', currentSlot: 7 }],
      slotPalettes: [
        {
          slot: 7,
          stops: [
            { position: 0, color: '#ff0000' },
            { position: 1, color: '#00ff00' },
          ],
        },
      ],
      activeGradientId: 'g0',
      paintSlot: 7,
    },
    version: 1,
  }) as Layer;

describe('resolveActiveColorCycleGradient', () => {
  it('uses active slot palette stops when stored gradient is empty', () => {
    const result = resolveActiveColorCycleGradient(createLayer(), createBrushSettings());

    expect(result.activeSlot).toBe(7);
    expect(result.activeStops).toEqual([
      { position: 0, color: '#ff0000' },
      { position: 1, color: '#00ff00' },
    ]);
  });
});
