import type { UseDrawingCanvasRuntimeEffectsHandlersOptions } from './useDrawingCanvasRuntimeEffectsHandlers';
import type { UseDrawingCanvasRuntimeEffectsFromStateOptions } from './useDrawingCanvasRuntimeEffectsFromState.types';
import { isColorCyclePlaybackActive } from './drawingCanvasRuntimeEffectsFromStateShared';

type BuildArgs = UseDrawingCanvasRuntimeEffectsFromStateOptions;

export const buildDrawingCanvasRuntimeEffectsFromStateInputArgs = ({
  state,
  renderRuntime,
  interactionRuntime,
  toolStateMachine,
  drawingHandlers,
  brushEngine,
  animationRuntime,
  draw,
  cursorStyle,
  setCursorStyle,
  showFeedback,
}: BuildArgs): UseDrawingCanvasRuntimeEffectsHandlersOptions['inputHandlersArgs'] => ({
  refs: {
    canvasRef: state.canvasElementRef,
    wrapperRef: state.wrapperElementRef,
    overlayCanvasRef: state.overlayCanvasElementRef,
    compositeCanvasRef: state.compositeCanvasRef,
    isBusyRef: state.isBusyRef,
    isMouseDownRef: state.isMouseDownRef,
    isSpacePressedRef: interactionRuntime.isSpacePressedRef,
    suppressBootstrapUntilPointerUpRef: interactionRuntime.suppressBootstrapUntilPointerUpRef,
    mousePositionRef: state.mousePositionRef,
    isZoomingRef: state.isZoomingRef,
    zoomEndTimeoutRef: state.zoomEndTimeoutRef,
    drawAnimationFrameRef: state.drawAnimationFrameRef,
    pointerMoveThrottled: state.pointerMoveThrottled,
    compositeCanvasDirtyRef: state.compositeCanvasDirtyRef,
    viewTransformRef: interactionRuntime.viewTransformRef,
    drawingAnimationFrameRef: state.drawingAnimationFrameRef,
    previewAnimationFrameRef: state.previewAnimationFrameRef,
  },
  state: {
    project: state.project,
    canvasZoom: state.canvasZoom,
    selectionMask: state.selectionMask,
    selectionMaskBounds: state.selectionMaskBounds,
    tools: state.tools,
    layers: state.layers,
    activeLayerId: state.activeLayerId,
    selectionStart: state.selectionStart,
    selectionEnd: state.selectionEnd,
    floatingPaste: state.floatingPaste,
    palette: state.palette,
    polygonGradientState: state.polygonGradientState,
    recolorSampling: state.recolorSampling,
    currentBrushPresetId: state.currentBrushPresetId,
    isDraggingFloatingPaste: state.isDraggingFloatingPaste,
    floatingPasteDragStart: state.floatingPasteDragStart,
    floatingPasteOriginalPos: state.floatingPasteOriginalPos,
    interaction: interactionRuntime.interaction,
    stateMachine: interactionRuntime.stateMachine,
    pan: interactionRuntime.pan,
    toolStateMachine,
    drawingHandlers,
    brushEngine,
    sampleColorAtPosition: renderRuntime.sampleColorAtPosition,
    sampleColorsAlongLine: renderRuntime.sampleColorsAlongLine,
    canvasShapeEditorActive: state.canvasShapeEditor.active,
    defaultCursorStyle: cursorStyle,
    brushShape: state.tools.brushSettings.brushShape,
    isColorCyclePlaybackActive,
  },
  actions: {
    setSelectionBounds: state.setSelectionBounds,
    clearSelection: state.clearSelection,
    extractSelectionToFloatingPaste: state.extractSelectionToFloatingPaste,
    setCurrentTool: state.setCurrentToolById,
    setCurrentOffscreenCanvas: state.setCurrentOffscreenCanvas,
    compositeLayersToCanvas: state.compositeLayersToCanvas,
    updateLayer: state.updateLayer,
    setActiveColor: state.setActiveColor,
    setBrushSettings: state.setBrushSettings,
    updateRecolorSampling: state.updateRecolorSampling,
    stopRecolorSampling: state.stopRecolorSampling,
    setRectangleBrushState: state.setRectangleBrushState,
    setCustomBrushFreehandPath: state.setCustomBrushFreehandPath,
    setFloatingPaste: state.setFloatingPasteFromHandlers,
    updateFloatingPastePosition: state.updateFloatingPastePosition,
    commitFloatingPaste: state.commitFloatingPaste,
    cancelFloatingPaste: state.cancelFloatingPaste,
    setIsDraggingFloatingPaste: state.setIsDraggingFloatingPaste,
    setCursorStyle,
    setShowBrushCursor: state.setShowBrushCursor,
    setCursorPosition: state.setCursorScreenPosition,
    setNeedsRedraw: state.setNeedsRedraw,
    setLayersNeedRecomposition: state.setLayersNeedRecomposition,
    setZoom: state.setZoom,
    setPan: interactionRuntime.setPan,
    draw,
  },
  animation: {
    wrappedStartAnimation: animationRuntime.wrappedStartAnimation,
    pauseAnimationForPan: animationRuntime.pauseAnimationForPan,
    resumeAnimationAfterPan: animationRuntime.resumeAnimationAfterPan,
    feedback: showFeedback,
  },
  clipboard: {
    selectionClipboardRef: state.selectionClipboardRef,
  },
});
